import { AssignmentType, AssignmentStatus } from '@prisma/client';

// Seed data for assignments
// All fields mapped from SQL, robust audit fields, type-safe
// Date math uses Date.now() for relative intervals

export const assignments = [
  // Python Programming Assignment (Course 1, Dr. John Williams)
  {
    tenant_id: 1,
    course_id: 1,
    teacher_id: 1,
    assignment_name: 'Python Project: Data Analysis',
    assignment_description: 'Analyze a dataset using Python and submit a Jupyter notebook with your findings.',
    assignment_type: AssignmentType.FILE_UPLOAD,
    total_marks: 20.0,
    passing_marks: 12.0,
    due_date: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000),
    allow_late_submissions: true,
    max_file_size_mb: 10,
    allowed_file_types: 'pdf,ipynb,py',
    max_attempts: 2,
    status: AssignmentStatus.PUBLISHED,
    instructions: 'Submit a well-documented notebook and a PDF report.',
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: 1,
    deleted_at: null,
    deleted_by: null,
    created_ip: '14.1.1.1',
    updated_ip: '14.1.1.2',
  },
  // Marketing Case Study (Course 2, Prof. Emily Clark)
  {
    tenant_id: 2,
    course_id: 2,
    teacher_id: 2,
    assignment_name: 'Case Study: Digital Marketing Campaign',
    assignment_description: 'Prepare a case study on a recent digital marketing campaign and analyze its effectiveness.',
    assignment_type: AssignmentType.FILE_UPLOAD,
    total_marks: 15.0,
    passing_marks: 9.0,
    due_date: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    allow_late_submissions: false,
    max_file_size_mb: 5,
    allowed_file_types: 'pdf,docx',
    max_attempts: 1,
    status: AssignmentStatus.PUBLISHED,
    instructions: 'Include campaign metrics and your recommendations.',
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 2,
    updated_by: 2,
    deleted_at: null,
    deleted_by: null,
    created_ip: '14.1.1.3',
    updated_ip: '14.1.1.4',
  },
  // Renewable Energy Lab Report (Course 3, Dr. Markus Schmidt)
  {
    tenant_id: 3,
    course_id: 3,
    teacher_id: 3,
    assignment_name: 'Lab Report: Solar Panel Efficiency',
    assignment_description: 'Conduct an experiment to measure the efficiency of different solar panels and submit your findings.',
    assignment_type: AssignmentType.FILE_UPLOAD,
    total_marks: 18.0,
    passing_marks: 10.0,
    due_date: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000),
    allow_late_submissions: true,
    max_file_size_mb: 8,
    allowed_file_types: 'pdf,docx',
    max_attempts: 2,
    status: AssignmentStatus.DRAFT,
    instructions: 'Attach photos of your setup and data tables.',
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 3,
    updated_by: 3,
    deleted_at: null,
    deleted_by: null,
    created_ip: '14.1.1.5',
    updated_ip: '14.1.1.6',
  },
  // Data Science Research Paper (Course 4, Dr. Priya Nair)
  {
    tenant_id: 1,
    course_id: 4,
    teacher_id: 4,
    assignment_name: 'Research Paper: Machine Learning Trends',
    assignment_description: 'Write a research paper on recent trends in machine learning and their applications.',
    assignment_type: AssignmentType.FILE_UPLOAD,
    total_marks: 25.0,
    passing_marks: 15.0,
    due_date: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000),
    allow_late_submissions: false,
    max_file_size_mb: 12,
    allowed_file_types: 'pdf,docx',
    max_attempts: 1,
    status: AssignmentStatus.PUBLISHED,
    instructions: 'Cite at least 5 recent research papers.',
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 4,
    updated_by: 4,
    deleted_at: null,
    deleted_by: null,
    created_ip: '14.1.1.7',
    updated_ip: '14.1.1.8',
  },
  // Clinical Psychology Reflection (Course 5, Prof. Matthew Evans)
  {
    tenant_id: 5,
    course_id: 5,
    teacher_id: 5,
    assignment_name: 'Reflection: Case Study in Clinical Psychology',
    assignment_description: 'Reflect on a clinical case and discuss the psychological assessment and intervention.',
    assignment_type: AssignmentType.FILE_UPLOAD,
    total_marks: 10.0,
    passing_marks: 6.0,
    due_date: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
    allow_late_submissions: true,
    max_file_size_mb: 5,
    allowed_file_types: 'pdf,docx',
    max_attempts: 2,
    status: AssignmentStatus.DRAFT,
    instructions: 'Use pseudonyms for all clients discussed.',
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 5,
    updated_by: 5,
    deleted_at: null,
    deleted_by: null,
    created_ip: '14.1.1.9',
    updated_ip: '14.1.2.0',
  },
];

export default assignments;
