// Seed data for cities
export const cities = [
  {
    state_id: 1,
    name: 'Los Angeles',
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: 2,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.0.0.1',
    updated_ip: '10.0.0.2',
  },
  {
    state_id: 1,
    name: 'San Francisco',
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.0.0.3',
    updated_ip: '10.0.0.4',
  },
  {
    state_id: 2,
    name: 'Houston',
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 2,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.0.0.5',
    updated_ip: '10.0.0.6',
  },
  {
    state_id: 3,
    name: 'Toronto',
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 3,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.0.0.7',
    updated_ip: '10.0.0.8',
  },
  {
    state_id: 3,
    name: 'Ottawa',
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 3,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.0.0.9',
    updated_ip: '10.0.1.0',
  },
  {
    state_id: 4,
    name: 'Vancouver',
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 4,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.0.1.1',
    updated_ip: '10.0.1.2',
  },
  {
    state_id: 5,
    name: 'London',
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 5,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.0.1.3',
    updated_ip: '10.0.1.4',
  },
  {
    state_id: 6,
    name: 'Sydney',
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 6,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.0.1.5',
    updated_ip: '10.0.1.6',
  },
  {
    state_id: 7,
    name: 'Munich',
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 7,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.0.1.7',
    updated_ip: '10.0.1.8',
  },
  {
    state_id: 8,
    name: 'Mumbai',
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 8,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.0.1.9',
    updated_ip: '10.0.2.0',
  },
];
