// Seed data for client tenants
export const client_tenants = [
  {
    client_id: 1,
    tenant_id: 1,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: 2,
    deleted_at: null,
    deleted_by: null,
    created_ip: '172.16.0.1',
    updated_ip: '172.16.0.2',
  },
  {
    client_id: 1,
    tenant_id: 2,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '172.16.0.3',
    updated_ip: '172.16.0.4',
  },
  {
    client_id: 2,
    tenant_id: 1,
    is_active: false,
    is_deleted: true,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 2,
    updated_by: 1,
    deleted_at: new Date(),
    deleted_by: 1,
    created_ip: '172.16.0.5',
    updated_ip: '172.16.0.6',
  },
  {
    client_id: 2,
    tenant_id: 3,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 2,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '172.16.0.7',
    updated_ip: '172.16.0.8',
  },
  {
    client_id: 3,
    tenant_id: 2,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 3,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '172.16.0.9',
    updated_ip: '172.16.1.0',
  },
  {
    client_id: 3,
    tenant_id: 3,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 3,
    updated_by: 2,
    deleted_at: null,
    deleted_by: null,
    created_ip: '172.16.1.1',
    updated_ip: '172.16.1.2',
  },
  {
    client_id: 4,
    tenant_id: 4,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 4,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '172.16.1.3',
    updated_ip: '172.16.1.4',
  },
  {
    client_id: 5,
    tenant_id: 5,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 5,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '172.16.1.5',
    updated_ip: '172.16.1.6',
  },
  {
    client_id: 4,
    tenant_id: 2,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 4,
    updated_by: 1,
    deleted_at: null,
    deleted_by: null,
    created_ip: '172.16.1.7',
    updated_ip: '172.16.1.8',
  },
  {
    client_id: 5,
    tenant_id: 1,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 5,
    updated_by: 2,
    deleted_at: null,
    deleted_by: null,
    created_ip: '172.16.1.9',
    updated_ip: '172.16.2.0',
  },
];
