// Seed data for clients
import { ClientStatus } from '@prisma/client';
export const clients = [
  {
    full_name: 'John Smith',
    email_address: 'john.smith@example.com',
    dial_code: '1',
    phone_number: '1234567890',
    address: '123 Main St, New York, NY',
    client_status: ClientStatus.ACTIVE,
    tenant_id: 1,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: 2,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.0.0.1',
    updated_ip: '10.0.0.2',
  },
  {
    full_name: 'Emily Davis',
    email_address: 'emily.davis@example.com',
    dial_code: '44',
    phone_number: '7700123456',
    address: '45 Park Lane, London',
    client_status: ClientStatus.INACTIVE,
    tenant_id: 2,
    is_active: false,
    is_deleted: true,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 2,
    updated_by: 3,
    deleted_at: new Date(),
    deleted_by: 3,
    created_ip: '10.0.0.3',
    updated_ip: '10.0.0.4',
  },
  {
    full_name: 'Ahmed Khan',
    email_address: 'ahmed.khan@example.com',
    dial_code: '92',
    phone_number: '3012345678',
    address: 'House 12, Street 5, Lahore',
    client_status: ClientStatus.SUSPENDED,
    tenant_id: 1,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.0.0.5',
    updated_ip: '10.0.0.6',
  },
  {
    full_name: 'Linda Nguyen',
    email_address: 'linda.nguyen@example.com',
    dial_code: '61',
    phone_number: '412345678',
    address: '22 George St, Sydney',
    client_status: ClientStatus.ACTIVE,
    tenant_id: 3,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 3,
    updated_by: 1,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.0.0.7',
    updated_ip: '10.0.0.8',
  },
  {
    full_name: 'Carlos Ruiz',
    email_address: 'carlos.ruiz@example.com',
    dial_code: '34',
    phone_number: '612345678',
    address: 'Calle Mayor, Madrid',
    client_status: ClientStatus.TERMINATED,
    tenant_id: 2,
    is_active: false,
    is_deleted: true,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 2,
    updated_by: 1,
    deleted_at: new Date(),
    deleted_by: 1,
    created_ip: '10.0.0.9',
    updated_ip: '10.0.0.10',
  },
  {
    full_name: 'Zara Ali',
    email_address: 'zara.ali@example.com',
    dial_code: '91',
    phone_number: '9812345678',
    address: 'Sector 5, Mumbai',
    client_status: ClientStatus.ACTIVE,
    tenant_id: 1,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.0.0.11',
    updated_ip: '10.0.0.12',
  },
  {
    full_name: 'Tom Becker',
    email_address: 'tom.becker@example.com',
    dial_code: '49',
    phone_number: '15123456789',
    address: 'Berlin Mitte',
    client_status: ClientStatus.SUSPENDED,
    tenant_id: 3,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 3,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.0.0.13',
    updated_ip: '10.0.0.14',
  },
  {
    full_name: 'Naomi Tanaka',
    email_address: 'naomi.tanaka@example.com',
    dial_code: '81',
    phone_number: '9012345678',
    address: 'Shibuya, Tokyo',
    client_status: ClientStatus.ACTIVE,
    tenant_id: 4,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 4,
    updated_by: 2,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.0.0.15',
    updated_ip: '10.0.0.16',
  },
  {
    full_name: 'Mohammed Salah',
    email_address: 'salah.m@example.com',
    dial_code: '20',
    phone_number: '1001234567',
    address: 'Cairo, Egypt',
    client_status: ClientStatus.INACTIVE,
    tenant_id: 2,
    is_active: false,
    is_deleted: true,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 2,
    updated_by: 1,
    deleted_at: new Date(),
    deleted_by: 1,
    created_ip: '10.0.0.17',
    updated_ip: '10.0.0.18',
  },
  {
    full_name: 'Olivia Brown',
    email_address: 'olivia.b@example.com',
    dial_code: '1',
    phone_number: '9876543210',
    address: 'San Francisco, CA',
    client_status: ClientStatus.ACTIVE,
    tenant_id: 1,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.0.0.19',
    updated_ip: '10.0.0.20',
  },
];
