// Seed data for countries
export const countries = [
  {
    name: 'United States',
    iso_code_2: 'US',
    iso_code_3: 'USA',
    dial_code: '+1',
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: 2,
    deleted_at: null,
    deleted_by: null,
    created_ip: '172.20.1.1',
    updated_ip: '172.20.1.2',
  },
  {
    name: 'Canada',
    iso_code_2: 'CA',
    iso_code_3: 'CAN',
    dial_code: '+1',
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '172.20.1.3',
    updated_ip: '172.20.1.4',
  },
  {
    name: 'United Kingdom',
    iso_code_2: 'GB',
    iso_code_3: 'GBR',
    dial_code: '+44',
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 2,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '172.20.1.5',
    updated_ip: '172.20.1.6',
  },
  {
    name: 'Australia',
    iso_code_2: 'AU',
    iso_code_3: 'AUS',
    dial_code: '+61',
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 2,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '172.20.1.7',
    updated_ip: '172.20.1.8',
  },
  {
    name: 'Germany',
    iso_code_2: 'DE',
    iso_code_3: 'DEU',
    dial_code: '+49',
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 3,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '172.20.1.9',
    updated_ip: '172.20.2.0',
  },
  {
    name: 'India',
    iso_code_2: 'IN',
    iso_code_3: 'IND',
    dial_code: '+91',
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 3,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '172.20.2.1',
    updated_ip: '172.20.2.2',
  },
  {
    name: 'Pakistan',
    iso_code_2: 'PK',
    iso_code_3: 'PAK',
    dial_code: '+92',
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 4,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '172.20.2.3',
    updated_ip: '172.20.2.4',
  },
  {
    name: 'France',
    iso_code_2: 'FR',
    iso_code_3: 'FRA',
    dial_code: '+33',
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 4,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '172.20.2.5',
    updated_ip: '172.20.2.6',
  },
  {
    name: 'UAE',
    iso_code_2: 'AE',
    iso_code_3: 'ARE',
    dial_code: '+971',
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '172.20.2.7',
    updated_ip: '172.20.2.8',
  },
  {
    name: 'Japan',
    iso_code_2: 'JP',
    iso_code_3: 'JPN',
    dial_code: '+81',
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 2,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '172.20.2.9',
    updated_ip: '172.20.3.0',
  },
];
