import { CourseStatus, CourseType } from '@prisma/client';
// Seed data for courses
export const courses = [
  {
    tenant_id: 1,
    program_id: 1,
    specialization_id: 1,
    course_name: 'May/June 2025',
    course_description: 'Business course covering fundamentals of management and strategy.',
    main_thumbnail_url: 'https://cdn.example.com/thumbnails/cs101.png',
    course_status: CourseStatus.PUBLIC,
    course_type: CourseType.PAID,
    course_price: 49.99,
    course_total_hours: 24.0,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.1.1.1',
    updated_ip: '11.1.1.2',
  },
  {
    tenant_id: 1,
    program_id: 1,
    specialization_id: 1,
    course_name: 'Nov/Dec 2025',
    course_description: 'Business course focusing on advanced topics in finance and marketing.',
    main_thumbnail_url: 'https://cdn.example.com/thumbnails/ba201.png',
    course_status: CourseStatus.PUBLIC,
    course_type: CourseType.FREE,
    course_price: null,
    course_total_hours: 18.0,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 2,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.1.1.3',
    updated_ip: '11.1.1.4',
  },
  {
    tenant_id: 1,
    program_id: 1,
    specialization_id: 2,
    course_name: 'May/June 2025',
    course_description: 'Physics course covering classical mechanics and thermodynamics.',
    main_thumbnail_url: 'https://cdn.example.com/thumbnails/en301.png',
    course_status: CourseStatus.DRAFT,
    course_type: CourseType.PAID,
    course_price: 79.99,
    course_total_hours: 30.0,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 3,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.1.1.5',
    updated_ip: '11.1.1.6',
  },
  {
    tenant_id: 1,
    program_id: 1,
    specialization_id: 2,
    course_name: 'Nov/Dec 2025',
    course_description: 'Physics course focusing on electromagnetism and optics.',
    main_thumbnail_url: 'https://cdn.example.com/thumbnails/cs202.png',
    course_status: CourseStatus.PUBLIC,
    course_type: CourseType.PAID,
    course_price: 59.99,
    course_total_hours: 28.0,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.1.1.7',
    updated_ip: '11.1.1.8',
  },
  {
    tenant_id: 5,
    program_id: 5,
    specialization_id: 6,
    course_name: 'Introduction to Clinical Psychology',
    course_description: 'Basics of clinical psychology and mental health.',
    main_thumbnail_url: 'https://cdn.example.com/thumbnails/psy101.png',
    course_status: CourseStatus.PUBLIC,
    course_type: CourseType.FREE,
    course_price: null,
    course_total_hours: 20.0,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 5,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.1.1.9',
    updated_ip: '11.1.2.0',
  },
];
