// Seed data for course documents
export const course_documents = [
  {
    tenant_id: 1,
    course_id: 1,
    course_topic_id: 1,
    document_name: 'Python Syntax Cheat Sheet',
    document_url: 'https://docs.example.com/python-syntax.pdf',
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.5.1.1',
    updated_ip: '11.5.1.2',
  },
  {
    tenant_id: 1,
    course_id: 1,
    course_topic_id: 2,
    document_name: 'Variables Guide',
    document_url: 'https://docs.example.com/variables.pdf',
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.5.1.3',
    updated_ip: '11.5.1.4',
  },
  {
    tenant_id: 1,
    course_id: 2,
    course_topic_id: 3,
    document_name: 'If Statements Reference',
    document_url: 'https://docs.example.com/if-statements.pdf',
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.5.1.5',
    updated_ip: '11.5.1.6',
  },
  {
    tenant_id: 1,
    course_id: 3,
    course_topic_id: 4,
    document_name: 'Solar Panel Types PDF',
    document_url: 'https://docs.example.com/solar-panels.pdf',
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 3,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.5.1.7',
    updated_ip: '11.5.1.8',
  },
  {
    tenant_id: 1,
    course_id: 4,
    course_topic_id: 5,
    document_name: 'Jupyter Notebooks Manual',
    document_url: 'https://docs.example.com/jupyter-notebooks.pdf',
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.5.1.9',
    updated_ip: '11.5.2.0',
  },
];
