import { CourseStatus, CourseType } from '@prisma/client';
// Seed data for courses
export const courses = [
  {
    tenant_id: 1,
    program_id: 1,
    specialization_id: 1,
    course_name: "May/June 2025",
    course_description: "Business course covering fundamentals of management and strategy.",
    main_thumbnail_url: "https://cdn.example.com/thumbnails/cs101.png'",
    course_status: CourseStatus.PUBLIC,
    course_type: CourseType.PAID,
    course_price: 49.99,
    course_total_hours: 24,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.1.1.1",
    updated_ip: "11.1.1.2"
  },
  {
    tenant_id: 1,
    program_id: 2,
    specialization_id: 2,
    course_name: "May/June 2025",
    course_description: "Economics - Salman Mustafa covering AS Eco Concepts",
    main_thumbnail_url: "https://cdn.example.com/thumbnails/cs101.png'",
    course_status: CourseStatus.PUBLIC,
    course_type: CourseType.PAID,
    course_price: 49.99,
    course_total_hours: 24,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.1.1.1",
    updated_ip: "11.1.1.2"
  },
  {
    tenant_id: 1,
    program_id: 3,
    specialization_id: 3,
    course_name: "May/June 2025",
    course_description: "Sociology - Shah Hasan covering OL Socio Concepts",
    main_thumbnail_url: "https://cdn.example.com/thumbnails/cs101.png'",
    course_status: CourseStatus.PUBLIC,
    course_type: CourseType.PAID,
    course_price: 49.99,
    course_total_hours: 24,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.1.1.1",
    updated_ip: "11.1.1.2"
  },
  {
    tenant_id: 1,
    program_id: 1,
    specialization_id: 4,
    course_name: "May/June 2025",
    course_description: "Economics  - Salman Mustafa covering A2 Eco Concepts",
    main_thumbnail_url: "https://cdn.example.com/thumbnails/cs101.png'",
    course_status: CourseStatus.PUBLIC,
    course_type: CourseType.PAID,
    course_price: 49.99,
    course_total_hours: 24,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.1.1.1",
    updated_ip: "11.1.1.2"
  },
  {
    tenant_id: 1,
    program_id: 3,
    specialization_id: 5,
    course_name: "May/June 2025",
    course_description: "Economics  - Salman Mustafa covering OL Eco Concepts",
    main_thumbnail_url: "https://cdn.example.com/thumbnails/cs101.png'",
    course_status: CourseStatus.PUBLIC,
    course_type: CourseType.PAID,
    course_price: 49.99,
    course_total_hours: 24,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.1.1.1",
    updated_ip: "11.1.1.2"
  },
  {
    tenant_id: 1,
    program_id: 2,
    specialization_id: 6,
    course_name: "May/June 2025",
    course_description: "Sociology - Shah Hasan covering AS Socio Concepts",
    main_thumbnail_url: "https://cdn.example.com/thumbnails/cs101.png'",
    course_status: CourseStatus.PUBLIC,
    course_type: CourseType.PAID,
    course_price: 49.99,
    course_total_hours: 24,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.1.1.1",
    updated_ip: "11.1.1.2"
  }
];
