
// Seed data for course session settings
export const course_session_settings = [
  {
    tenant_id: 1,
    course_session_id: 1,
    allow_late_enrollment: true,
    require_approval_for_enrollment: false,
    allow_student_discussions: true,
    send_reminder_emails: true,
    reminder_days_before_expiry: 7,
    grading_scale: { A: 90, B: 80, C: 70, D: 60, F: 0 },
    attendance_tracking_enabled: true,
    is_active: true,
    is_deleted: false,
    created_at: new Date(Date.now() - 100 * 24 * 60 * 60 * 1000), // 100 days ago
    created_by: 1,
    created_ip: '10.62.1.1',
    updated_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000), // 30 days ago
    updated_by: 1,
    updated_ip: '10.62.1.2',
    deleted_at: null,
    deleted_by: null,
  },
  {
    tenant_id: 1,
    course_session_id: 2,
    allow_late_enrollment: false,
    require_approval_for_enrollment: true,
    allow_student_discussions: true,
    send_reminder_emails: true,
    reminder_days_before_expiry: 5,
    grading_scale: { A: 85, B: 75, C: 65, D: 55, F: 0 },
    attendance_tracking_enabled: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(Date.now() - 190 * 24 * 60 * 60 * 1000), // 190 days ago
    created_by: 2,
    created_ip: '10.62.1.3',
    updated_at: new Date(Date.now() - 120 * 24 * 60 * 60 * 1000), // 120 days ago
    updated_by: 2,
    updated_ip: '10.62.1.4',
    deleted_at: null,
    deleted_by: null,
  },
  {
    tenant_id: 1,
    course_session_id: 3,
    allow_late_enrollment: true,
    require_approval_for_enrollment: false,
    allow_student_discussions: true,
    send_reminder_emails: false,
    reminder_days_before_expiry: 10,
    grading_scale: { A: 92, B: 82, C: 72, D: 62, F: 0 },
    attendance_tracking_enabled: true,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    created_by: 3,
    created_ip: '10.62.1.5',
    updated_at: null,
    updated_by: null,
    updated_ip: null,
    deleted_at: null,
    deleted_by: null,
  },
  {
    tenant_id: 1,
    course_session_id: 4,
    allow_late_enrollment: false,
    require_approval_for_enrollment: false,
    allow_student_discussions: true,
    send_reminder_emails: true,
    reminder_days_before_expiry: 7,
    grading_scale: { A: 88, B: 78, C: 68, D: 58, F: 0 },
    attendance_tracking_enabled: true,
    is_active: true,
    is_deleted: false,
    created_at: new Date(Date.now() - 70 * 24 * 60 * 60 * 1000), // 70 days ago
    created_by: 4,
    created_ip: '10.62.1.6',
    updated_at: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000), // 30 days from now
    updated_by: 4,
    updated_ip: '10.62.1.7',
    deleted_at: null,
    deleted_by: null,
  },
  {
    tenant_id: 1,
    course_session_id: 5,
    allow_late_enrollment: false,
    require_approval_for_enrollment: true,
    allow_student_discussions: false,
    send_reminder_emails: false,
    reminder_days_before_expiry: 3,
    grading_scale: { A: 90, B: 80, C: 70, D: 60, F: 0 },
    attendance_tracking_enabled: false,
    is_active: false,
    is_deleted: true,
    created_at: new Date(Date.now() - 310 * 24 * 60 * 60 * 1000), // 310 days ago
    created_by: 5,
    created_ip: '10.62.1.8',
    updated_at: new Date(Date.now() - 250 * 24 * 60 * 60 * 1000), // 250 days ago
    updated_by: 5,
    updated_ip: '10.62.1.9',
    deleted_at: null,
    deleted_by: null,
  },
];
