// Seed data for course modules
export const course_modules = [
  {
    tenant_id: 1,
    course_id: 1,
    course_module_name: 'Unit 1',
    position: 1,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.2.1.1',
    updated_ip: '11.2.1.2',
  },
  {
    tenant_id: 1,
    course_id: 1,
    course_module_name: 'Unit 2',
    position: 2,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.2.1.3',
    updated_ip: '11.2.1.4',
  },
  {
    tenant_id: 1,
    course_id: 1,
    course_module_name: 'Unit 3',
    position: 1,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 2,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.2.1.5',
    updated_ip: '11.2.1.6',
  },
  {
    tenant_id: 1,
    course_id: 3,
    course_module_name: 'Circular Motion',
    position: 1,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 3,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.2.1.7',
    updated_ip: '11.2.1.8',
  },
  {
    tenant_id: 1,
    course_id: 3,
    course_module_name: 'Gravition',
    position: 1,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.2.1.9',
    updated_ip: '11.2.2.0',
  },
  {
    tenant_id: 1,
    course_id: 3,
    course_module_name: 'Thermal',
    position: 1,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 5,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.2.2.1',
    updated_ip: '11.2.2.2',
  },
];
