// Seed data for course specializations (junction table for Course <-> Specialization)
export const course_specializations = [
  {
    course_id: 1,
    specialization_id: 1,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.1.2.1",
    updated_ip: "11.1.2.2",
  },
  {
    course_id: 2,
    specialization_id: 2,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.1.2.1",
    updated_ip: "11.1.2.2",
  },
  {
    course_id: 3,
    specialization_id: 3,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.1.2.1",
    updated_ip: "11.1.2.2",
  },
  {
    course_id: 4,
    specialization_id: 4,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.1.2.1",
    updated_ip: "11.1.2.2",
  },
  {
    course_id: 5,
    specialization_id: 5,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.1.2.1",
    updated_ip: "11.1.2.2",
  },
  {
    course_id: 6,
    specialization_id: 6,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.1.2.1",
    updated_ip: "11.1.2.2",
  },
];