// Seed data for course modules
export const course_modules = [
  {
    tenant_id: 1,
    course_id: 1,
    course_module_name: 'Getting Started with Python',
    position: 1,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.2.1.1',
    updated_ip: '11.2.1.2',
  },
  {
    tenant_id: 1,
    course_id: 1,
    course_module_name: 'Control Structures',
    position: 2,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.2.1.3',
    updated_ip: '11.2.1.4',
  },
  {
    tenant_id: 1,
    course_id: 2,
    course_module_name: 'Marketing Basics',
    position: 1,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 2,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.2.1.5',
    updated_ip: '11.2.1.6',
  },
  {
    tenant_id: 1,
    course_id: 3,
    course_module_name: 'Solar Power',
    position: 1,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 3,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.2.1.7',
    updated_ip: '11.2.1.8',
  },
  {
    tenant_id: 1,
    course_id: 4,
    course_module_name: 'Data Analysis Tools',
    position: 1,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.2.1.9',
    updated_ip: '11.2.2.0',
  },
  {
    tenant_id: 1,
    course_id: 5,
    course_module_name: 'Foundations of Clinical Psychology',
    position: 1,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 5,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.2.2.1',
    updated_ip: '11.2.2.2',
  },
];
