// Seed data for course topics
export const course_topics = [
  {
    tenant_id: 1,
    module_id: 1,
    course_topic_name: 'Python Syntax',
    position: 1,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.3.1.1',
    updated_ip: '11.3.1.2',
  },
  {
    tenant_id: 1,
    module_id: 1,
    course_topic_name: 'Variables and Data Types',
    position: 2,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.3.1.3',
    updated_ip: '11.3.1.4',
  },
  {
    tenant_id: 1,
    module_id: 2,
    course_topic_name: 'If Statements',
    position: 1,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.3.1.5',
    updated_ip: '11.3.1.6',
  },
  {
    tenant_id: 1,
    module_id: 3,
    course_topic_name: 'Solar Panel Types',
    position: 1,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 3,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.3.1.7',
    updated_ip: '11.3.1.8',
  },
  {
    tenant_id: 1,
    module_id: 4,
    course_topic_name: 'Jupyter Notebooks',
    position: 1,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.3.1.9',
    updated_ip: '11.3.2.0',
  },
  {
    tenant_id: 1,
    module_id: 5,
    course_topic_name: 'History of Clinical Psychology',
    position: 1,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 5,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.3.2.1',
    updated_ip: '11.3.2.2',
  },
];
