import { CourseStatus, CourseType } from '@prisma/client';
// Seed data for courses
export const courses = [
  {
    tenant_id: 1,
    program_id: 1,
    specialization_id: 1,
    course_name: 'Introduction to Programming',
    course_description: 'Learn the basics of programming using Python.',
    main_thumbnail_url: 'https://cdn.example.com/thumbnails/cs101.png',
    course_status: CourseStatus.PUBLISHED,
    course_type: CourseType.PAID,
    course_price: 49.99,
    course_total_hours: 24.0,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.1.1.1',
    updated_ip: '11.1.1.2',
  },
  {
    tenant_id: 2,
    program_id: 2,
    specialization_id: 3,
    course_name: 'Principles of Marketing',
    course_description: 'Fundamentals of marketing in a digital world.',
    main_thumbnail_url: 'https://cdn.example.com/thumbnails/ba201.png',
    course_status: CourseStatus.PUBLISHED,
    course_type: CourseType.FREE,
    course_price: null,
    course_total_hours: 18.0,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 2,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.1.1.3',
    updated_ip: '11.1.1.4',
  },
  {
    tenant_id: 3,
    program_id: 3,
    specialization_id: 5,
    course_name: 'Renewable Energy Systems',
    course_description: 'Overview of renewable energy technologies.',
    main_thumbnail_url: 'https://cdn.example.com/thumbnails/en301.png',
    course_status: CourseStatus.DRAFT,
    course_type: CourseType.PAID,
    course_price: 79.99,
    course_total_hours: 30.0,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 3,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.1.1.5',
    updated_ip: '11.1.1.6',
  },
  {
    tenant_id: 1,
    program_id: 1,
    specialization_id: 2,
    course_name: 'Data Science Fundamentals',
    course_description: 'Introduction to data science concepts and tools.',
    main_thumbnail_url: 'https://cdn.example.com/thumbnails/cs202.png',
    course_status: CourseStatus.PUBLISHED,
    course_type: CourseType.PAID,
    course_price: 59.99,
    course_total_hours: 28.0,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.1.1.7',
    updated_ip: '11.1.1.8',
  },
  {
    tenant_id: 5,
    program_id: 5,
    specialization_id: 6,
    course_name: 'Introduction to Clinical Psychology',
    course_description: 'Basics of clinical psychology and mental health.',
    main_thumbnail_url: 'https://cdn.example.com/thumbnails/psy101.png',
    course_status: CourseStatus.PUBLISHED,
    course_type: CourseType.FREE,
    course_price: null,
    course_total_hours: 20.0,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 5,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.1.1.9',
    updated_ip: '11.1.2.0',
  },
];
