// Seed data for course topics
export const course_topics = [
  {
    tenant_id: 1,
    module_id: 1,
    course_topic_name: "Business Strategy",
    position: 1,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.3.1.1",
    updated_ip: "11.3.1.2",
  },
  {
    tenant_id: 1,
    module_id: 2,
    course_topic_name: "Basic Economic Problem",
    position: 1,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.3.1.1",
    updated_ip: "11.3.1.2",
  },
  {
    tenant_id: 1,
    module_id: 2,
    course_topic_name: "PPC",
    position: 2,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.3.1.1",
    updated_ip: "11.3.1.2",
  },
  {
    tenant_id: 1,
    module_id: 2,
    course_topic_name: "Demand",
    position: 3,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.3.1.1",
    updated_ip: "11.3.1.2",
  },
  {
    tenant_id: 1,
    module_id: 3,
    course_topic_name: "NIS",
    position: 1,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.3.1.1",
    updated_ip: "11.3.1.2",
  },
  {
    tenant_id: 1,
    module_id: 3,
    course_topic_name: "Inflation",
    position: 2,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.3.1.1",
    updated_ip: "11.3.1.2",
  },
  {
    tenant_id: 1,
    module_id: 3,
    course_topic_name: "policies",
    position: 3,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.3.1.1",
    updated_ip: "11.3.1.2",
  },
  {
    tenant_id: 1,
    module_id: 4,
    course_topic_name: "s21_11",
    position: 1,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.3.1.1",
    updated_ip: "11.3.1.2",
  },
  {
    tenant_id: 1,
    module_id: 4,
    course_topic_name: "s21_12",
    position: 2,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.3.1.1",
    updated_ip: "11.3.1.2",
  },
  {
    tenant_id: 1,
    module_id: 5,
    course_topic_name: "Consumer theory",
    position: 1,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.3.1.1",
    updated_ip: "11.3.1.2",
  },
  {
    tenant_id: 1,
    module_id: 5,
    course_topic_name: "Costs",
    position: 2,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.3.1.1",
    updated_ip: "11.3.1.2",
  },
  {
    tenant_id: 1,
    module_id: 5,
    course_topic_name: "Market Failure",
    position: 3,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.3.1.1",
    updated_ip: "11.3.1.2",
  },
  {
    tenant_id: 1,
    module_id: 6,
    course_topic_name: "Economic Growth",
    position: 1,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.3.1.1",
    updated_ip: "11.3.1.2",
  },
  {
    tenant_id: 1,
    module_id: 6,
    course_topic_name: "Supply Side Policy",
    position: 2,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.3.1.1",
    updated_ip: "11.3.1.2",
  },
  {
    tenant_id: 1,
    module_id: 7,
    course_topic_name: "s21_41",
    position: 3,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.3.1.1",
    updated_ip: "11.3.1.2",
  },
  {
    tenant_id: 1,
    module_id: 7,
    course_topic_name: "s21_42",
    position: 4,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.3.1.1",
    updated_ip: "11.3.1.2",
  },
  {
    tenant_id: 1,
    module_id: 8,
    course_topic_name: "Basic Economic Problem",
    position: 1,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.3.1.1",
    updated_ip: "11.3.1.2",
  },
  {
    tenant_id: 1,
    module_id: 8,
    course_topic_name: "Government Intervention",
    position: 2,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.3.1.1",
    updated_ip: "11.3.1.2",
  },
  {
    tenant_id: 1,
    module_id: 9,
    course_topic_name: "AD/AS",
    position: 1,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.3.1.1",
    updated_ip: "11.3.1.2",
  },
  {
    tenant_id: 1,
    module_id: 9,
    course_topic_name: "Exchange Rate",
    position: 2,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.3.1.1",
    updated_ip: "11.3.1.2",
  },
  {
    tenant_id: 1,
    module_id: 10,
    course_topic_name: "s21_22",
    position: 1,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.3.1.1",
    updated_ip: "11.3.1.2",
  },
  {
    tenant_id: 1,
    module_id: 10,
    course_topic_name: "s21_22",
    position: 2,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.3.1.1",
    updated_ip: "11.3.1.2",
  },
  {
    tenant_id: 1,
    module_id: 11,
    course_topic_name: "Socialisation",
    position: 1,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.3.1.1",
    updated_ip: "11.3.1.2",
  },
  {
    tenant_id: 1,
    module_id: 11,
    course_topic_name: "Social Idenity",
    position: 2,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.3.1.1",
    updated_ip: "11.3.1.2",
  },
  {
    tenant_id: 1,
    module_id: 12,
    course_topic_name: "Family Structure",
    position: 1,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.3.1.1",
    updated_ip: "11.3.1.2",
  },
  {
    tenant_id: 1,
    module_id: 12,
    course_topic_name: "Community",
    position: 2,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.3.1.1",
    updated_ip: "11.3.1.2",
  },
  {
    tenant_id: 1,
    module_id: 13,
    course_topic_name: "Education",
    position: 1,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.3.1.1",
    updated_ip: "11.3.1.2",
  },
  {
    tenant_id: 1,
    module_id: 13,
    course_topic_name: "Education II",
    position: 2,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.3.1.1",
    updated_ip: "11.3.1.2",
  },
  {
    tenant_id: 1,
    module_id: 14,
    course_topic_name: "Religion",
    position: 1,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.3.1.1",
    updated_ip: "11.3.1.2",
  },
  {
    tenant_id: 1,
    module_id: 14,
    course_topic_name: "Religion II",
    position: 2,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.3.1.1",
    updated_ip: "11.3.1.2",
  },
];
