import { VideoUploadStatus } from "@prisma/client";
// Seed data for course videos
export const course_videos = [

  // COURSE BY NAWAID ALI - MAY/JUNE 2025
  {
    tenant_id: 1,
    course_id: 3,
    course_topic_id: 1,
    bunny_video_id: '9fde8760-e49b-40f6-9680-c681137093eb',
    video_name: 'Circular Motion Basics',
    video_url: 'https://videos.example.com/python-syntax.mp4',
    thumbnail_url: null,
    duration_seconds: 600,
    position: 1,
    upload_status: VideoUploadStatus.COMPLETED,
    is_locked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.4.1.1',
    updated_ip: '11.4.1.2',
  },
  {
    tenant_id: 1,
    course_id: 3,
    course_topic_id: 1,
    bunny_video_id: '9fde8760-e49b-40f6-9680-c681137093eb',
    video_name: 'Circular Motion Advanced',
    video_url: 'https://videos.example.com/variables.mp4',
    thumbnail_url: null,
    duration_seconds: 540,
    position: 2,
    upload_status: VideoUploadStatus.COMPLETED,
    is_locked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.4.1.3',
    updated_ip: '11.4.1.4',
  },
  {
    tenant_id: 1,
    course_id: 3,
    course_topic_id: 2,
    bunny_video_id: '9c66200b-3325-47a7-a286-af4303a3f971',
    video_name: 'Gravitational Forces',
    video_url: 'https://videos.example.com/if-statements.mp4',
    thumbnail_url: null,
    duration_seconds: 480,
    position: 1,
    upload_status: VideoUploadStatus.COMPLETED,
    is_locked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.4.1.5',
    updated_ip: '11.4.1.6',
  },
  {
    tenant_id: 1,
    course_id: 3,
    course_topic_id: 2,
    bunny_video_id: '9c66200b-3325-47a7-a286-af4303a3f971',
    video_name: 'Gravitation Advanced',
    video_url: 'https://videos.example.com/solar-panels.mp4',
    thumbnail_url: null,
    duration_seconds: 720,
    position: 1,
    upload_status: VideoUploadStatus.COMPLETED,
    is_locked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 3,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.4.1.7',
    updated_ip: '11.4.1.8',
  },
  {
    tenant_id: 1,
    course_id: 3,
    course_topic_id: 3,
    bunny_video_id: '687638e9-deb7-4882-9380-dea9065efc70',
    video_name: 'Thermal Sec A',
    video_url: 'https://videos.example.com/jupyter-notebooks.mp4',
    thumbnail_url: null,
    duration_seconds: 900,
    position: 1,
    upload_status: VideoUploadStatus.COMPLETED,
    is_locked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.4.1.9',
    updated_ip: '11.4.2.0',
  },
  {
    tenant_id: 1,
    course_id: 3,
    course_topic_id: 4,
    bunny_video_id: '687638e9-deb7-4882-9380-dea9065efc70',
    video_name: 'Thermal Sec B',
    video_url: 'https://iframe.mediadelivery.net/embed/459051/65444e39-a0f8-4467-95a7-94f8571915d1',
    thumbnail_url: null,
    duration_seconds: 900,
    position: 1,
    upload_status: VideoUploadStatus.COMPLETED,
    is_locked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.4.1.9',
    updated_ip: '11.4.2.0',
  },

  // COURSE BY NAWAID ALI -- NOV/DEC 2025
  
  {
    tenant_id: 1,
    course_id: 4,
    course_topic_id: 1,
    bunny_video_id: '9fde8760-e49b-40f6-9680-c681137093eb',
    video_name: 'Circular Motion Basics',
    video_url: 'https://videos.example.com/python-syntax.mp4',
    thumbnail_url: null,
    duration_seconds: 600,
    position: 1,
    upload_status: VideoUploadStatus.COMPLETED,
    is_locked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.4.1.1',
    updated_ip: '11.4.1.2',
  },
  {
    tenant_id: 1,
    course_id: 4,
    course_topic_id: 1,
    bunny_video_id: '9fde8760-e49b-40f6-9680-c681137093eb',
    video_name: 'Circular Motion Advanced',
    video_url: 'https://videos.example.com/variables.mp4',
    thumbnail_url: null,
    duration_seconds: 540,
    position: 2,
    upload_status: VideoUploadStatus.COMPLETED,
    is_locked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.4.1.3',
    updated_ip: '11.4.1.4',
  },
  {
    tenant_id: 1,
    course_id: 4,
    course_topic_id: 2,
    bunny_video_id: '9c66200b-3325-47a7-a286-af4303a3f971',
    video_name: 'Gravitational Forces',
    video_url: 'https://videos.example.com/if-statements.mp4',
    thumbnail_url: null,
    duration_seconds: 480,
    position: 1,
    upload_status: VideoUploadStatus.COMPLETED,
    is_locked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.4.1.5',
    updated_ip: '11.4.1.6',
  },
  {
    tenant_id: 1,
    course_id: 4,
    course_topic_id: 2,
    bunny_video_id: '9c66200b-3325-47a7-a286-af4303a3f971',
    video_name: 'Gravitation Advanced',
    video_url: 'https://videos.example.com/solar-panels.mp4',
    thumbnail_url: null,
    duration_seconds: 720,
    position: 1,
    upload_status: VideoUploadStatus.COMPLETED,
    is_locked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 3,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.4.1.7',
    updated_ip: '11.4.1.8',
  },
  {
    tenant_id: 1,
    course_id: 4,
    course_topic_id: 3,
    bunny_video_id: '687638e9-deb7-4882-9380-dea9065efc70',
    video_name: 'Thermal Sec A',
    video_url: 'https://videos.example.com/jupyter-notebooks.mp4',
    thumbnail_url: null,
    duration_seconds: 900,
    position: 1,
    upload_status: VideoUploadStatus.COMPLETED,
    is_locked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.4.1.9',
    updated_ip: '11.4.2.0',
  },
  {
    tenant_id: 1,
    course_id: 4,
    course_topic_id: 4,
    bunny_video_id: '687638e9-deb7-4882-9380-dea9065efc70',
    video_name: 'Thermal Sec B',
    video_url: 'https://iframe.mediadelivery.net/embed/459051/65444e39-a0f8-4467-95a7-94f8571915d1',
    thumbnail_url: null,
    duration_seconds: 900,
    position: 1,
    upload_status: VideoUploadStatus.COMPLETED,
    is_locked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.4.1.9',
    updated_ip: '11.4.2.0',
  },

  // COURSE BY OMAR ALTAF - MAY/JUNE 2025
  
  {
    tenant_id: 1,
    course_id: 1,
    course_topic_id: 7,
    bunny_video_id: '6499d1b5-2bee-4843-9b66-2809f2627f02',
    video_name: 'Business Strategy Basics',
    video_url: 'https://videos.example.com/python-syntax.mp4',
    thumbnail_url: null,
    duration_seconds: 600,
    position: 1,
    upload_status: VideoUploadStatus.COMPLETED,
    is_locked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.4.1.1',
    updated_ip: '11.4.1.2',
  },
  {
    tenant_id: 1,
    course_id: 1,
    course_topic_id: 7,
    bunny_video_id: '128a62e1-038c-421d-b4ca-9beb715383da',
    video_name: 'Business Strategy Advanced',
    video_url: 'https://videos.example.com/variables.mp4',
    thumbnail_url: null,
    duration_seconds: 540,
    position: 2,
    upload_status: VideoUploadStatus.COMPLETED,
    is_locked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.4.1.3',
    updated_ip: '11.4.1.4',
  },
  {
    tenant_id: 1,
    course_id: 1,
    course_topic_id: 7,
    bunny_video_id: 'b04c03dd-4bf1-46c7-a5cf-e23075260663',
    video_name: 'Business Strategy Deep Dive',
    video_url: 'https://videos.example.com/if-statements.mp4',
    thumbnail_url: null,
    duration_seconds: 480,
    position: 1,
    upload_status: VideoUploadStatus.COMPLETED,
    is_locked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.4.1.5',
    updated_ip: '11.4.1.6',
  },
  {
    tenant_id: 1,
    course_id: 1,
    course_topic_id: 8,
    bunny_video_id: '6499d1b5-2bee-4843-9b66-2809f2627f02',
    video_name: 'Strategic Planning Basics',
    video_url: 'https://videos.example.com/solar-panels.mp4',
    thumbnail_url: null,
    duration_seconds: 720,
    position: 1,
    upload_status: VideoUploadStatus.COMPLETED,
    is_locked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 3,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.4.1.7',
    updated_ip: '11.4.1.8',
  },
  {
    tenant_id: 1,
    course_id: 1,
    course_topic_id: 8,
    bunny_video_id: '128a62e1-038c-421d-b4ca-9beb715383da',
    video_name: 'Strategic Planning Advanced',
    video_url: 'https://videos.example.com/jupyter-notebooks.mp4',
    thumbnail_url: null,
    duration_seconds: 900,
    position: 1,
    upload_status: VideoUploadStatus.COMPLETED,
    is_locked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.4.1.9',
    updated_ip: '11.4.2.0',
  },
  {
    tenant_id: 1,
    course_id: 1,
    course_topic_id: 8,
    bunny_video_id: 'b04c03dd-4bf1-46c7-a5cf-e23075260663',
    video_name: 'Strategic Planning Deep Dive',
    video_url: 'https://iframe.mediadelivery.net/embed/459051/65444e39-a0f8-4467-95a7-94f8571915d1',
    thumbnail_url: null,
    duration_seconds: 900,
    position: 1,
    upload_status: VideoUploadStatus.COMPLETED,
    is_locked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.4.1.9',
    updated_ip: '11.4.2.0',
  },
  {
    tenant_id: 1,
    course_id: 1,
    course_topic_id: 9,
    bunny_video_id: '6499d1b5-2bee-4843-9b66-2809f2627f02',
    video_name: 'Strategic Implementation',
    video_url: 'https://videos.example.com/python-syntax.mp4',
    thumbnail_url: null,
    duration_seconds: 600,
    position: 1,
    upload_status: VideoUploadStatus.COMPLETED,
    is_locked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.4.1.1',
    updated_ip: '11.4.1.2',
  },
  {
    tenant_id: 1,
    course_id: 1,
    course_topic_id: 10,
    bunny_video_id: '6499d1b5-2bee-4843-9b66-2809f2627f02',
    video_name: 'Organisational Structure',
    video_url: 'https://videos.example.com/python-syntax.mp4',
    thumbnail_url: null,
    duration_seconds: 600,
    position: 1,
    upload_status: VideoUploadStatus.COMPLETED,
    is_locked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.4.1.1',
    updated_ip: '11.4.1.2',
  },
  {
    tenant_id: 1,
    course_id: 1,
    course_topic_id: 11,
    bunny_video_id: '128a62e1-038c-421d-b4ca-9beb715383da',
    video_name: 'Business Communication',
    video_url: 'https://videos.example.com/variables.mp4',
    thumbnail_url: null,
    duration_seconds: 540,
    position: 2,
    upload_status: VideoUploadStatus.COMPLETED,
    is_locked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.4.1.3',
    updated_ip: '11.4.1.4',
  },
  {
    tenant_id: 1,
    course_id: 1,
    course_topic_id: 12,
    bunny_video_id: 'b04c03dd-4bf1-46c7-a5cf-e23075260663',
    video_name: 'Human Resource Management',
    video_url: 'https://videos.example.com/if-statements.mp4',
    thumbnail_url: null,
    duration_seconds: 480,
    position: 1,
    upload_status: VideoUploadStatus.COMPLETED,
    is_locked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.4.1.5',
    updated_ip: '11.4.1.6',
  },
  {
    tenant_id: 1,
    course_id: 1,
    course_topic_id: 13,
    bunny_video_id: '6499d1b5-2bee-4843-9b66-2809f2627f02',
    video_name: 'Leadership Skills',
    video_url: 'https://videos.example.com/solar-panels.mp4',
    thumbnail_url: null,
    duration_seconds: 720,
    position: 1,
    upload_status: VideoUploadStatus.COMPLETED,
    is_locked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 3,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.4.1.7',
    updated_ip: '11.4.1.8',
  },

  // COURSE BY OMAR ALTAF -- NOV/DEC 2025
  {
    tenant_id: 1,
    course_id: 1,
    course_topic_id: 7,
    bunny_video_id: '6499d1b5-2bee-4843-9b66-2809f2627f02',
    video_name: 'Business Strategy Basics',
    video_url: 'https://videos.example.com/python-syntax.mp4',
    thumbnail_url: null,
    duration_seconds: 600,
    position: 1,
    upload_status: VideoUploadStatus.COMPLETED,
    is_locked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.4.1.1',
    updated_ip: '11.4.1.2',
  },
  {
    tenant_id: 1,
    course_id: 1,
    course_topic_id: 7,
    bunny_video_id: '128a62e1-038c-421d-b4ca-9beb715383da',
    video_name: 'Business Strategy Advanced',
    video_url: 'https://videos.example.com/variables.mp4',
    thumbnail_url: null,
    duration_seconds: 540,
    position: 2,
    upload_status: VideoUploadStatus.COMPLETED,
    is_locked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.4.1.3',
    updated_ip: '11.4.1.4',
  },
  {
    tenant_id: 1,
    course_id: 1,
    course_topic_id: 7,
    bunny_video_id: 'b04c03dd-4bf1-46c7-a5cf-e23075260663',
    video_name: 'Business Strategy Deep Dive',
    video_url: 'https://videos.example.com/if-statements.mp4',
    thumbnail_url: null,
    duration_seconds: 480,
    position: 1,
    upload_status: VideoUploadStatus.COMPLETED,
    is_locked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.4.1.5',
    updated_ip: '11.4.1.6',
  },
  {
    tenant_id: 1,
    course_id: 1,
    course_topic_id: 8,
    bunny_video_id: '6499d1b5-2bee-4843-9b66-2809f2627f02',
    video_name: 'Strategic Planning Basics',
    video_url: 'https://videos.example.com/solar-panels.mp4',
    thumbnail_url: null,
    duration_seconds: 720,
    position: 1,
    upload_status: VideoUploadStatus.COMPLETED,
    is_locked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 3,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.4.1.7',
    updated_ip: '11.4.1.8',
  },
  {
    tenant_id: 1,
    course_id: 1,
    course_topic_id: 8,
    bunny_video_id: '128a62e1-038c-421d-b4ca-9beb715383da',
    video_name: 'Strategic Planning Advanced',
    video_url: 'https://videos.example.com/jupyter-notebooks.mp4',
    thumbnail_url: null,
    duration_seconds: 900,
    position: 1,
    upload_status: VideoUploadStatus.COMPLETED,
    is_locked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.4.1.9',
    updated_ip: '11.4.2.0',
  },
  {
    tenant_id: 1,
    course_id: 1,
    course_topic_id: 8,
    bunny_video_id: 'b04c03dd-4bf1-46c7-a5cf-e23075260663',
    video_name: 'Strategic Planning Deep Dive',
    video_url: 'https://iframe.mediadelivery.net/embed/459051/65444e39-a0f8-4467-95a7-94f8571915d1',
    thumbnail_url: null,
    duration_seconds: 900,
    position: 1,
    upload_status: VideoUploadStatus.COMPLETED,
    is_locked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.4.1.9',
    updated_ip: '11.4.2.0',
  },
  {
    tenant_id: 1,
    course_id: 1,
    course_topic_id: 9,
    bunny_video_id: '6499d1b5-2bee-4843-9b66-2809f2627f02',
    video_name: 'Strategic Implementation',
    video_url: 'https://videos.example.com/python-syntax.mp4',
    thumbnail_url: null,
    duration_seconds: 600,
    position: 1,
    upload_status: VideoUploadStatus.COMPLETED,
    is_locked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.4.1.1',
    updated_ip: '11.4.1.2',
  },
  {
    tenant_id: 1,
    course_id: 1,
    course_topic_id: 10,
    bunny_video_id: '6499d1b5-2bee-4843-9b66-2809f2627f02',
    video_name: 'Organisational Structure',
    video_url: 'https://videos.example.com/python-syntax.mp4',
    thumbnail_url: null,
    duration_seconds: 600,
    position: 1,
    upload_status: VideoUploadStatus.COMPLETED,
    is_locked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.4.1.1',
    updated_ip: '11.4.1.2',
  },
  {
    tenant_id: 1,
    course_id: 1,
    course_topic_id: 11,
    bunny_video_id: '128a62e1-038c-421d-b4ca-9beb715383da',
    video_name: 'Business Communication',
    video_url: 'https://videos.example.com/variables.mp4',
    thumbnail_url: null,
    duration_seconds: 540,
    position: 2,
    upload_status: VideoUploadStatus.COMPLETED,
    is_locked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.4.1.3',
    updated_ip: '11.4.1.4',
  },
  {
    tenant_id: 1,
    course_id: 1,
    course_topic_id: 12,
    bunny_video_id: 'b04c03dd-4bf1-46c7-a5cf-e23075260663',
    video_name: 'Human Resource Management',
    video_url: 'https://videos.example.com/if-statements.mp4',
    thumbnail_url: null,
    duration_seconds: 480,
    position: 1,
    upload_status: VideoUploadStatus.COMPLETED,
    is_locked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.4.1.5',
    updated_ip: '11.4.1.6',
  },
  {
    tenant_id: 1,
    course_id: 1,
    course_topic_id: 13,
    bunny_video_id: '6499d1b5-2bee-4843-9b66-2809f2627f02',
    video_name: 'Leadership Skills',
    video_url: 'https://videos.example.com/solar-panels.mp4',
    thumbnail_url: null,
    duration_seconds: 720,
    position: 1,
    upload_status: VideoUploadStatus.COMPLETED,
    is_locked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 3,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.4.1.7',
    updated_ip: '11.4.1.8',
  },
];
