import { VideoUploadStatus } from "@prisma/client";
// Seed data for course videos
export const course_videos = [
  {
    tenant_id: 1,
    course_id: 3,
    course_topic_id: 1,
    bunny_video_id: "9fde8760-e49b-40f6-9680-c681137093eb",
    video_name: "Business Strategy",
    video_url: "https://videos.example.com/python-syntax.mp4",
    thumbnail_url: null,
    duration_seconds: 600,
    position: 1,
    upload_status: VideoUploadStatus.COMPLETED,
    is_locked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.4.1.1",
    updated_ip: "11.4.1.2",
  },
  {
    tenant_id: 1,
    course_id: 2,
    course_topic_id: 2,
    bunny_video_id: "9fde8760-e49b-40f6-9680-c681137093eb",
    video_name: "Basic Economic Problem",
    video_url: "https://videos.example.com/python-syntax.mp4",
    thumbnail_url: null,
    duration_seconds: 600,
    position: 1,
    upload_status: VideoUploadStatus.COMPLETED,
    is_locked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.4.1.1",
    updated_ip: "11.4.1.2",
  },
  {
    tenant_id: 1,
    course_id: 2,
    course_topic_id: 3,
    bunny_video_id: "9fde8760-e49b-40f6-9680-c681137093eb",
    video_name: "PPC",
    video_url: "https://videos.example.com/python-syntax.mp4",
    thumbnail_url: null,
    duration_seconds: 600,
    position: 1,
    upload_status: VideoUploadStatus.COMPLETED,
    is_locked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.4.1.1",
    updated_ip: "11.4.1.2",
  },
  {
    tenant_id: 1,
    course_id: 2,
    course_topic_id: 4,
    bunny_video_id: "9fde8760-e49b-40f6-9680-c681137093eb",
    video_name: "Demand",
    video_url: "https://videos.example.com/python-syntax.mp4",
    thumbnail_url: null,
    duration_seconds: 600,
    position: 1,
    upload_status: VideoUploadStatus.COMPLETED,
    is_locked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.4.1.1",
    updated_ip: "11.4.1.2",
  },
  {
    tenant_id: 1,
    course_id: 2,
    course_topic_id: 5,
    bunny_video_id: "9fde8760-e49b-40f6-9680-c681137093eb",
    video_name: "NIS",
    video_url: "https://videos.example.com/python-syntax.mp4",
    thumbnail_url: null,
    duration_seconds: 600,
    position: 1,
    upload_status: VideoUploadStatus.COMPLETED,
    is_locked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.4.1.1",
    updated_ip: "11.4.1.2",
  },
  {
    tenant_id: 1,
    course_id: 2,
    course_topic_id: 6,
    bunny_video_id: "9fde8760-e49b-40f6-9680-c681137093eb",
    video_name: "Supply",
    video_url: "https://videos.example.com/python-syntax.mp4",
    thumbnail_url: null,
    duration_seconds: 600,
    position: 1,
    upload_status: VideoUploadStatus.COMPLETED,
    is_locked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.4.1.1",
    updated_ip: "11.4.1.2",
  },
  {
    tenant_id: 1,
    course_id: 2,
    course_topic_id: 7,
    bunny_video_id: "9fde8760-e49b-40f6-9680-c681137093eb",
    video_name: "Elasticity",
    video_url: "https://videos.example.com/python-syntax.mp4",
    thumbnail_url: null,
    duration_seconds: 600,
    position: 1,
    upload_status: VideoUploadStatus.COMPLETED,
    is_locked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.4.1.1",
    updated_ip: "11.4.1.2",
  },
  {
    tenant_id: 1,
    course_id: 2,
    course_topic_id: 8,
    bunny_video_id: "9fde8760-e49b-40f6-9680-c681137093eb",
    video_name: "Market Structure",
    video_url: "https://videos.example.com/python-syntax.mp4",
    thumbnail_url: null,
    duration_seconds: 600,
    position: 1,
    upload_status: VideoUploadStatus.COMPLETED,
    is_locked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.4.1.1",
    updated_ip: "11.4.1.2",
  },
  {
    tenant_id: 1,
    course_id: 2,
    course_topic_id: 9,
    bunny_video_id: "9fde8760-e49b-40f6-9680-c681137093eb",
    video_name: "Production",
    video_url: "https://videos.example.com/python-syntax.mp4",
    thumbnail_url: null,
    duration_seconds: 600,
    position: 1,
    upload_status: VideoUploadStatus.COMPLETED,
    is_locked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.4.1.1",
    updated_ip: "11.4.1.2",
  },
  {
    tenant_id: 1,
    course_id: 2,
    course_topic_id: 10,
    bunny_video_id: "9fde8760-e49b-40f6-9680-c681137093eb",
    video_name: "Cost",
    video_url: "https://videos.example.com/python-syntax.mp4",
    thumbnail_url: null,
    duration_seconds: 600,
    position: 1,
    upload_status: VideoUploadStatus.COMPLETED,
    is_locked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.4.1.1",
    updated_ip: "11.4.1.2",
  },
    {
    tenant_id: 1,
    course_id: 2,
    course_topic_id: 11,
    bunny_video_id: "9fde8760-e49b-40f6-9680-c681137093eb",
    video_name: "Market Failure",
    video_url: "https://videos.example.com/market-failure.mp4",
    thumbnail_url: null,
    duration_seconds: 600,
    position: 1,
    upload_status: VideoUploadStatus.COMPLETED,
    is_locked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.4.1.1",
    updated_ip: "11.4.1.2",
  },
  {
    tenant_id: 1,
    course_id: 2,
    course_topic_id: 12,
    bunny_video_id: "9fde8760-e49b-40f6-9680-c681137093eb",
    video_name: "Economic Growth",
    video_url: "https://videos.example.com/economic-growth.mp4",
    thumbnail_url: null,
    duration_seconds: 600,
    position: 1,
    upload_status: VideoUploadStatus.COMPLETED,
    is_locked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.4.1.1",
    updated_ip: "11.4.1.2",
  },
  {
    tenant_id: 1,
    course_id: 2,
    course_topic_id: 13,
    bunny_video_id: "9fde8760-e49b-40f6-9680-c681137093eb",
    video_name: "Supply Side Policy",
    video_url: "https://videos.example.com/supply-side-policy.mp4",
    thumbnail_url: null,
    duration_seconds: 600,
    position: 1,
    upload_status: VideoUploadStatus.COMPLETED,
    is_locked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.4.1.1",
    updated_ip: "11.4.1.2",
  },
  {
    tenant_id: 1,
    course_id: 2,
    course_topic_id: 14,
    bunny_video_id: "9fde8760-e49b-40f6-9680-c681137093eb",
    video_name: "s21_41",
    video_url: "https://videos.example.com/s21_41.mp4",
    thumbnail_url: null,
    duration_seconds: 600,
    position: 1,
    upload_status: VideoUploadStatus.COMPLETED,
    is_locked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.4.1.1",
    updated_ip: "11.4.1.2",
  },
  {
    tenant_id: 1,
    course_id: 2,
    course_topic_id: 15,
    bunny_video_id: "9fde8760-e49b-40f6-9680-c681137093eb",
    video_name: "s21_42",
    video_url: "https://videos.example.com/s21_42.mp4",
    thumbnail_url: null,
    duration_seconds: 600,
    position: 1,
    upload_status: VideoUploadStatus.COMPLETED,
    is_locked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.4.1.1",
    updated_ip: "11.4.1.2",
  },
  {
    tenant_id: 1,
    course_id: 2,
    course_topic_id: 16,
    bunny_video_id: "9fde8760-e49b-40f6-9680-c681137093eb",
    video_name: "Basic Economic Problem II",
    video_url: "https://videos.example.com/basic-economic-problem-2.mp4",
    thumbnail_url: null,
    duration_seconds: 600,
    position: 1,
    upload_status: VideoUploadStatus.COMPLETED,
    is_locked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.4.1.1",
    updated_ip: "11.4.1.2",
  },
  {
    tenant_id: 1,
    course_id: 2,
    course_topic_id: 17,
    bunny_video_id: "9fde8760-e49b-40f6-9680-c681137093eb",
    video_name: "Government Intervention",
    video_url: "https://videos.example.com/government-intervention.mp4",
    thumbnail_url: null,
    duration_seconds: 600,
    position: 1,
    upload_status: VideoUploadStatus.COMPLETED,
    is_locked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.4.1.1",
    updated_ip: "11.4.1.2",
  },
  {
    tenant_id: 1,
    course_id: 2,
    course_topic_id: 18,
    bunny_video_id: "9fde8760-e49b-40f6-9680-c681137093eb",
    video_name: "AD/AS",
    video_url: "https://videos.example.com/ad-as.mp4",
    thumbnail_url: null,
    duration_seconds: 600,
    position: 1,
    upload_status: VideoUploadStatus.COMPLETED,
    is_locked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.4.1.1",
    updated_ip: "11.4.1.2",
  },
  {
    tenant_id: 1,
    course_id: 2,
    course_topic_id: 19,
    bunny_video_id: "9fde8760-e49b-40f6-9680-c681137093eb",
    video_name: "Exchange Rate",
    video_url: "https://videos.example.com/exchange-rate.mp4",
    thumbnail_url: null,
    duration_seconds: 600,
    position: 1,
    upload_status: VideoUploadStatus.COMPLETED,
    is_locked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.4.1.1",
    updated_ip: "11.4.1.2",
  },
  {
    tenant_id: 1,
    course_id: 2,
    course_topic_id: 20,
    bunny_video_id: "9fde8760-e49b-40f6-9680-c681137093eb",
    video_name: "s21_22",
    video_url: "https://videos.example.com/s21_22.mp4",
    thumbnail_url: null,
    duration_seconds: 600,
    position: 1,
    upload_status: VideoUploadStatus.COMPLETED,
    is_locked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.4.1.1",
    updated_ip: "11.4.1.2",
  },
  {
    tenant_id: 1,
    course_id: 2,
    course_topic_id: 21,
    bunny_video_id: "9fde8760-e49b-40f6-9680-c681137093eb",
    video_name: "s21_22 II",
    video_url: "https://videos.example.com/s21_22-2.mp4",
    thumbnail_url: null,
    duration_seconds: 600,
    position: 1,
    upload_status: VideoUploadStatus.COMPLETED,
    is_locked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.4.1.1",
    updated_ip: "11.4.1.2",
  },
    {
    tenant_id: 1,
    course_id: 3,
    course_topic_id: 22,
    bunny_video_id: "9fde8760-e49b-40f6-9680-c681137093eb",
    video_name: "Socialisation",
    video_url: "https://videos.example.com/socialisation.mp4",
    thumbnail_url: null,
    duration_seconds: 600,
    position: 1,
    upload_status: VideoUploadStatus.COMPLETED,
    is_locked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.4.1.1",
    updated_ip: "11.4.1.2",
  },
  {
    tenant_id: 1,
    course_id: 3,
    course_topic_id: 23,
    bunny_video_id: "9fde8760-e49b-40f6-9680-c681137093eb",
    video_name: "Social Identity",
    video_url: "https://videos.example.com/social-identity.mp4",
    thumbnail_url: null,
    duration_seconds: 600,
    position: 1,
    upload_status: VideoUploadStatus.COMPLETED,
    is_locked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.4.1.1",
    updated_ip: "11.4.1.2",
  },
  {
    tenant_id: 1,
    course_id: 3,
    course_topic_id: 24,
    bunny_video_id: "9fde8760-e49b-40f6-9680-c681137093eb",
    video_name: "Family Structure",
    video_url: "https://videos.example.com/family-structure.mp4",
    thumbnail_url: null,
    duration_seconds: 600,
    position: 1,
    upload_status: VideoUploadStatus.COMPLETED,
    is_locked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.4.1.1",
    updated_ip: "11.4.1.2",
  },
  {
    tenant_id: 1,
    course_id: 3,
    course_topic_id: 25,
    bunny_video_id: "9fde8760-e49b-40f6-9680-c681137093eb",
    video_name: "Community",
    video_url: "https://videos.example.com/community.mp4",
    thumbnail_url: null,
    duration_seconds: 600,
    position: 1,
    upload_status: VideoUploadStatus.COMPLETED,
    is_locked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.4.1.1",
    updated_ip: "11.4.1.2",
  },
  {
    tenant_id: 1,
    course_id: 6,
    course_topic_id: 26,
    bunny_video_id: "9fde8760-e49b-40f6-9680-c681137093eb",
    video_name: "Education",
    video_url: "https://videos.example.com/education.mp4",
    thumbnail_url: null,
    duration_seconds: 600,
    position: 1,
    upload_status: VideoUploadStatus.COMPLETED,
    is_locked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.4.1.1",
    updated_ip: "11.4.1.2",
  },
  {
    tenant_id: 1,
    course_id: 6,
    course_topic_id: 27,
    bunny_video_id: "9fde8760-e49b-40f6-9680-c681137093eb",
    video_name: "Education II",
    video_url: "https://videos.example.com/education-2.mp4",
    thumbnail_url: null,
    duration_seconds: 600,
    position: 1,
    upload_status: VideoUploadStatus.COMPLETED,
    is_locked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.4.1.1",
    updated_ip: "11.4.1.2",
  },
  {
    tenant_id: 1,
    course_id: 6,
    course_topic_id: 28,
    bunny_video_id: "9fde8760-e49b-40f6-9680-c681137093eb",
    video_name: "Religion",
    video_url: "https://videos.example.com/religion.mp4",
    thumbnail_url: null,
    duration_seconds: 600,
    position: 1,
    upload_status: VideoUploadStatus.COMPLETED,
    is_locked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.4.1.1",
    updated_ip: "11.4.1.2",
  },
  {
    tenant_id: 1,
    course_id: 6,
    course_topic_id: 29,
    bunny_video_id: "9fde8760-e49b-40f6-9680-c681137093eb",
    video_name: "Religion II",
    video_url: "https://videos.example.com/religion-2.mp4",
    thumbnail_url: null,
    duration_seconds: 600,
    position: 1,
    upload_status: VideoUploadStatus.COMPLETED,
    is_locked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.4.1.1",
    updated_ip: "11.4.1.2",
  },
  {
    tenant_id: 1,
    course_id: 6,
    course_topic_id: 30,
    bunny_video_id: "9fde8760-e49b-40f6-9680-c681137093eb",
    video_name: "Religion III",
    video_url: "https://videos.example.com/religion-3.mp4",
    thumbnail_url: null,
    duration_seconds: 600,
    position: 1,
    upload_status: VideoUploadStatus.COMPLETED,
    is_locked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.4.1.1",
    updated_ip: "11.4.1.2",
  }
];
