import { VideoUploadStatus } from "@prisma/client";
// Seed data for course videos
export const course_videos = [
  {
    tenant_id: 1,
    course_id: 1,
    course_topic_id: 1,
    bunny_video_id: 'bunny-vid-001',
    video_name: 'Python Syntax Overview',
    video_url: 'https://videos.example.com/python-syntax.mp4',
    thumbnail_url: null,
    duration_seconds: 600,
    position: 1,
    upload_status: VideoUploadStatus.COMPLETED,
    IsLocked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.4.1.1',
    updated_ip: '11.4.1.2',
  },
  {
    tenant_id: 1,
    course_id: 1,
    course_topic_id: 2,
    bunny_video_id: 'bunny-vid-002',
    video_name: 'Variables Explained',
    video_url: 'https://videos.example.com/variables.mp4',
    thumbnail_url: null,
    duration_seconds: 540,
    position: 2,
    upload_status: VideoUploadStatus.COMPLETED,
    IsLocked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.4.1.3',
    updated_ip: '11.4.1.4',
  },
  {
    tenant_id: 1,
    course_id: 2,
    course_topic_id: 3,
    bunny_video_id: 'bunny-vid-003',
    video_name: 'If Statements in Action',
    video_url: 'https://videos.example.com/if-statements.mp4',
    thumbnail_url: null,
    duration_seconds: 480,
    position: 1,
    upload_status: VideoUploadStatus.COMPLETED,
    IsLocked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.4.1.5',
    updated_ip: '11.4.1.6',
  },
  {
    tenant_id: 1,
    course_id: 3,
    course_topic_id: 4,
    bunny_video_id: 'bunny-vid-004',
    video_name: 'Solar Panel Types',
    video_url: 'https://videos.example.com/solar-panels.mp4',
    thumbnail_url: null,
    duration_seconds: 720,
    position: 1,
    upload_status: VideoUploadStatus.COMPLETED,
    IsLocked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 3,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.4.1.7',
    updated_ip: '11.4.1.8',
  },
  {
    tenant_id: 1,
    course_id: 4,
    course_topic_id: 5,
    bunny_video_id: 'bunny-vid-005',
    video_name: 'Jupyter Notebooks Demo',
    video_url: 'https://videos.example.com/jupyter-notebooks.mp4',
    thumbnail_url: null,
    duration_seconds: 900,
    position: 1,
    upload_status: VideoUploadStatus.COMPLETED,
    IsLocked: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '11.4.1.9',
    updated_ip: '11.4.2.0',
  },
];
