// Seed data for course modules
export const course_modules = [
  {
    tenant_id: 1,
    course_id: 1,
    course_module_name: "Unit 1",
    position: 1,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.2.1.1",
    updated_ip: "11.2.1.2",
  },
  {
    tenant_id: 1,
    course_id: 2,
    course_module_name: "Microeconomics",
    position: 1,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.2.1.1",
    updated_ip: "11.2.1.2",
  },
  {
    tenant_id: 1,
    course_id: 2,
    course_module_name: "Macroeconomics",
    position: 2,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.2.1.1",
    updated_ip: "11.2.1.2",
  },
  {
    tenant_id: 1,
    course_id: 2,
    course_module_name: "Pastpapers",
    position: 3,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.2.1.1",
    updated_ip: "11.2.1.2",
  },
  {
    tenant_id: 1,
    course_id: 4,
    course_module_name: "Microeconomics",
    position: 1,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.2.1.1",
    updated_ip: "11.2.1.2",
  },
  {
    tenant_id: 1,
    course_id: 4,
    course_module_name: "Macroeconomics",
    position: 2,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.2.1.1",
    updated_ip: "11.2.1.2",
  },
  {
    tenant_id: 1,
    course_id: 4,
    course_module_name: "Pastpapers",
    position: 3,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.2.1.1",
    updated_ip: "11.2.1.2",
  },
  {
    tenant_id: 1,
    course_id: 5,
    course_module_name: "Microeconomics",
    position: 1,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.2.1.1",
    updated_ip: "11.2.1.2",
  },
  {
    tenant_id: 1,
    course_id: 5,
    course_module_name: "Macroeconomics",
    position: 2,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.2.1.1",
    updated_ip: "11.2.1.2",
  },
  {
    tenant_id: 1,
    course_id: 5,
    course_module_name: "Pastpapers",
    position: 3,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.2.1.1",
    updated_ip: "11.2.1.2",
  },
  {
    tenant_id: 1,
    course_id: 3,
    course_module_name: "Paper 1",
    position: 1,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.2.1.1",
    updated_ip: "11.2.1.2",
  },
  {
    tenant_id: 1,
    course_id: 3,
    course_module_name: "Paper 2",
    position: 2,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.2.1.1",
    updated_ip: "11.2.1.2",
  },
  {
    tenant_id: 1,
    course_id: 6,
    course_module_name: "Paper 1",
    position: 1,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.2.1.1",
    updated_ip: "11.2.1.2",
  },
  {
    tenant_id: 1,
    course_id: 6,
    course_module_name: "Paper 2",
    position: 2,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: "11.2.1.1",
    updated_ip: "11.2.1.2",
  },
];
