import { EnrollmentStatus } from "@prisma/client";
// Seed data for enrollment status histories
export const enrollment_status_histories = [
  {
    tenant_id: 1,
    enrollment_id: 1,
    previous_status: EnrollmentStatus.PENDING,
    new_status: EnrollmentStatus.ACTIVE,
    status_changed_at: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000), // 60 days ago
    changed_by: 1,
    change_reason: 'Initial activation',
    notes: 'Enrolled by admin',
    is_active: true,
    is_deleted: false,
    created_at: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000), // 60 days ago
    created_by: 1,
    created_ip: '10.51.1.1',
    updated_at: null,
    updated_by: null,
    updated_ip: null,
    deleted_at: null,
    deleted_by: null,
  },
  {
    tenant_id: 1,
    enrollment_id: 2,
    previous_status: EnrollmentStatus.PENDING,
    new_status: EnrollmentStatus.ACTIVE,
    status_changed_at: new Date(Date.now() - 120 * 24 * 60 * 60 * 1000), // 120 days ago
    changed_by: 2,
    change_reason: 'Activated by admin',
    notes: null,
    is_active: true,
    is_deleted: false,
    created_at: new Date(Date.now() - 120 * 24 * 60 * 60 * 1000), // 120 days ago
    created_by: 2,
    created_ip: '10.51.1.2',
    updated_at: null,
    updated_by: null,
    updated_ip: null,
    deleted_at: null,
    deleted_by: null,
  },
  {
    tenant_id: 1,
    enrollment_id: 2,
    previous_status: EnrollmentStatus.ACTIVE,
    new_status: EnrollmentStatus.COMPLETED,
    status_changed_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000), // 10 days ago
    changed_by: 2,
    change_reason: 'Course completed',
    notes: 'Final grade B+',
    is_active: true,
    is_deleted: false,
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000), // 10 days ago
    created_by: 2,
    created_ip: '10.51.1.3',
    updated_at: null,
    updated_by: null,
    updated_ip: null,
    deleted_at: null,
    deleted_by: null,
  },
  {
    tenant_id: 1,
    enrollment_id: 4,
    previous_status: EnrollmentStatus.PENDING,
    new_status: EnrollmentStatus.ACTIVE,
    status_changed_at: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000), // 20 days ago
    changed_by: 4,
    change_reason: 'Activated by admin',
    notes: null,
    is_active: true,
    is_deleted: false,
    created_at: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000), // 20 days ago
    created_by: 4,
    created_ip: '10.51.1.4',
    updated_at: null,
    updated_by: null,
    updated_ip: null,
    deleted_at: null,
    deleted_by: null,
  },
  {
    tenant_id: 1,
    enrollment_id: 5,
    previous_status: EnrollmentStatus.PENDING,
    new_status: EnrollmentStatus.ACTIVE,
    status_changed_at: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000), // 90 days ago
    changed_by: 5,
    change_reason: 'Activated by admin',
    notes: null,
    is_active: true,
    is_deleted: false,
    created_at: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000), // 90 days ago
    created_by: 5,
    created_ip: '10.51.1.5',
    updated_at: null,
    updated_by: null,
    updated_ip: null,
    deleted_at: null,
    deleted_by: null,
  },
  {
    tenant_id: 1,
    enrollment_id: 5,
    previous_status: EnrollmentStatus.ACTIVE,
    new_status: EnrollmentStatus.DROPPED,
    status_changed_at: new Date(Date.now() - 70 * 24 * 60 * 60 * 1000), // 70 days ago
    changed_by: 5,
    change_reason: 'Withdrew due to personal reasons',
    notes: 'Student requested withdrawal',
    is_active: true,
    is_deleted: false,
    created_at: new Date(Date.now() - 70 * 24 * 60 * 60 * 1000), // 70 days ago
    created_by: 5,
    created_ip: '10.51.1.6',
    updated_at: null,
    updated_by: null,
    updated_ip: null,
    deleted_at: null,
    deleted_by: null,
  },
];
