// Seed data for academic institutes
// All fields mapped from SQL, robust and type-safe
export const institutes = [
  {
    tenant_id: 1,
    institute_name: 'School of Engineering',
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.1.3.3',
    updated_ip: '10.1.3.4',
  },
  {
    tenant_id: 2,
    institute_name: 'School of Business',
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 2,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.1.3.5',
    updated_ip: '10.1.3.6',
  },
  {
    tenant_id: 3,
    institute_name: 'Institute of Environmental Studies',
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 3,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.1.3.7',
    updated_ip: '10.1.3.8',
  },
  {
    tenant_id: 4,
    institute_name: 'College of Arts and Sciences',
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 4,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.1.3.9',
    updated_ip: '10.1.4.0',
  },
  {
    tenant_id: 5,
    institute_name: 'School of Health Sciences',
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 5,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.1.4.1',
    updated_ip: '10.1.4.2',
  },
];
