// Seed data for programs
export const programs = [
  {
    tenant_id: 1,
    program_name: 'Computer Science',
    program_thumbnail_url: null,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.1.1.1',
    updated_ip: '10.1.1.2',
  },
  {
    tenant_id: 2,
    program_name: 'Business Administration',
    program_thumbnail_url: null,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 2,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.1.1.3',
    updated_ip: '10.1.1.4',
  },
  {
    tenant_id: 3,
    program_name: 'Environmental Science',
    program_thumbnail_url: null,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 3,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.1.1.5',
    updated_ip: '10.1.1.6',
  },
  {
    tenant_id: 4,
    program_name: 'Mechanical Engineering',
    program_thumbnail_url: null,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 4,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.1.1.7',
    updated_ip: '10.1.1.8',
  },
  {
    tenant_id: 5,
    program_name: 'Psychology',
    program_thumbnail_url: null,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 5,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.1.1.9',
    updated_ip: '10.1.2.0',
  },
];
