import { QuizQuestionType } from '@prisma/client';
// Seed data for quiz questions
export const quiz_questions = [
  {
    tenant_id: 1,
    quiz_id: 1,
    teacher_id: 1,
    question_text: 'What is the correct file extension for Python files?',
    question_type: QuizQuestionType.MULTIPLE_CHOICE_SINGLE_ANSWER,
    question_marks: 2.0,
    position: 1,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '12.3.1.1',
    updated_ip: '12.3.1.2',
  },
  {
    tenant_id: 1,
    quiz_id: 1,
    teacher_id: 1,
    question_text: 'Which of the following is a valid variable name in Python?',
    question_type: QuizQuestionType.MULTIPLE_CHOICE_SINGLE_ANSWER,
    question_marks: 2.0,
    position: 2,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '12.3.1.3',
    updated_ip: '12.3.1.4',
  },
  {
    tenant_id: 1,
    quiz_id: 1,
    teacher_id: 1,
    question_text: 'Python is a case-sensitive language.',
    question_type: QuizQuestionType.TRUE_FALSE,
    question_marks: 1.0,
    position: 3,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '12.3.1.5',
    updated_ip: '12.3.1.6',
  },
  {
    tenant_id: 1,
    quiz_id: 2,
    teacher_id: 2,
    question_text: 'Which of the following is NOT a marketing principle?',
    question_type: QuizQuestionType.MULTIPLE_CHOICE_SINGLE_ANSWER,
    question_marks: 3.0,
    position: 1,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 2,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '12.3.1.7',
    updated_ip: '12.3.1.8',
  },
  {
    tenant_id: 1,
    quiz_id: 2,
    teacher_id: 2,
    question_text: 'Marketing is only about selling products.',
    question_type: QuizQuestionType.TRUE_FALSE,
    question_marks: 2.0,
    position: 2,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 2,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '12.3.1.9',
    updated_ip: '12.3.2.0',
  },
  {
    tenant_id: 1,
    quiz_id: 3,
    teacher_id: 3,
    question_text: 'Which energy source is renewable?',
    question_type: QuizQuestionType.MULTIPLE_CHOICE_SINGLE_ANSWER,
    question_marks: 2.0,
    position: 1,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 3,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '12.3.2.1',
    updated_ip: '12.3.2.2',
  },
];
