
// Seed data for quiz question answers
export const quiz_question_answers = [
  {
    tenant_id: 1,
    quiz_question_id: 1,
    answer_text: '.py',
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '13.1.1.1',
    updated_ip: '13.1.1.2',
  },
  {
    tenant_id: 1,
    quiz_question_id: 2,
    answer_text: 'my_var',
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '13.1.1.3',
    updated_ip: '13.1.1.4',
  },
  {
    tenant_id: 1,
    quiz_question_id: 3,
    answer_text: 'True',
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '13.1.1.5',
    updated_ip: '13.1.1.6',
  },
  {
    tenant_id: 1,
    quiz_question_id: 4,
    answer_text: 'Procrastination',
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 2,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '13.1.1.7',
    updated_ip: '13.1.1.8',
  },
  {
    tenant_id: 1,
    quiz_question_id: 5,
    answer_text: 'False',
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 2,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '13.1.1.9',
    updated_ip: '13.1.2.0',
  },
  {
    tenant_id: 1,
    quiz_question_id: 6,
    answer_text: 'Solar',
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 3,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '13.1.2.1',
    updated_ip: '13.1.2.2',
  },
];
