import { QuizStatus } from '@prisma/client';
// Seed data for quizzes
export const quizzes = [
  {
    tenant_id: 1,
    course_id: 1,
    teacher_id: 1,
    quiz_name: 'Python Basics Quiz',
    quiz_description: 'Quiz on Python basics and syntax.',
    total_marks: 20.0,
    passing_marks: 12.0,
    time_limit_minutes: 30,
    max_attempts: 2,
    allow_retake: true,
    randomize_questions: true,
    due_date: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000), // 7 days from now
    status: QuizStatus.PUBLISHED,
    instructions: 'Answer all questions. Passing is 60%.',
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '12.1.1.1',
    updated_ip: '12.1.1.2',
  },
  {
    tenant_id: 1,
    course_id: 2,
    teacher_id: 2,
    quiz_name: 'Marketing Fundamentals Quiz',
    quiz_description: 'Quiz on marketing principles.',
    total_marks: 15.0,
    passing_marks: 9.0,
    time_limit_minutes: 20,
    max_attempts: 1,
    allow_retake: false,
    randomize_questions: true,
    due_date: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000), // 10 days from now
    status: QuizStatus.PUBLISHED,
    instructions: 'No negative marking.',
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 2,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '12.1.1.3',
    updated_ip: '12.1.1.4',
  },
  {
    tenant_id: 1,
    course_id: 3,
    teacher_id: 3,
    quiz_name: 'Renewable Energy Quiz',
    quiz_description: 'Quiz on renewable energy systems.',
    total_marks: 18.0,
    passing_marks: 10.0,
    time_limit_minutes: 25,
    max_attempts: 2,
    allow_retake: true,
    randomize_questions: false,
    due_date: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000), // 15 days from now
    status: QuizStatus.DRAFT,
    instructions: 'Attempt all questions.',
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 3,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '12.1.1.5',
    updated_ip: '12.1.1.6',
  },
];
