import { QuizReferenceTable } from '@prisma/client';
// Seed data for quiz mappings
export const quiz_mappings = [
  {
    tenant_id: 1,
    quiz_id: 1,
    reference_table_type: QuizReferenceTable.COURSE,
    reference_id: 1,
    teacher_id: 1,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '12.2.1.1',
    updated_ip: '12.2.1.2',
  },
  {
    tenant_id: 1,
    quiz_id: 1,
    reference_table_type: QuizReferenceTable.COURSE_MODULE,
    reference_id: 1,
    teacher_id: 1,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '12.2.1.3',
    updated_ip: '12.2.1.4',
  },
  {
    tenant_id: 1,
    quiz_id: 1,
    reference_table_type: QuizReferenceTable.COURSE_TOPIC,
    reference_id: 1,
    teacher_id: 1,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '12.2.1.5',
    updated_ip: '12.2.1.6',
  },
  {
    tenant_id: 1,
    quiz_id: 2,
    reference_table_type: QuizReferenceTable.COURSE,
    reference_id: 2,
    teacher_id: 2,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 2,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '12.2.1.7',
    updated_ip: '12.2.1.8',
  },
  {
    tenant_id: 1,
    quiz_id: 3,
    reference_table_type: QuizReferenceTable.COURSE,
    reference_id: 3,
    teacher_id: 3,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 3,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '12.2.1.9',
    updated_ip: '12.2.2.0',
  },
];
