// Quiz Attempt Answers seed data
// All fields mapped from SQL, robust audit fields, type-safe
// Date math uses Date.now() for relative intervals

export const quiz_attempt_answers = [
  // Sarah Johnson (attempt 1, quiz 1)
  {
    tenant_id: 1,
    quiz_attempt_id: 1,
    quiz_question_id: 1,
    quiz_question_option_id: 1,
    answer_text: null,
    is_correct: true,
    marks_obtained: 2.0,
    reviewed_by_teacher_id: 1,
    teacher_comment: 'Correct answer.',
    is_active: true,
    is_deleted: false,
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    updated_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    created_by: 1,
    updated_by: 1,
    deleted_at: null,
    deleted_by: null,
    created_ip: '13.3.1.1',
    updated_ip: '13.3.1.2',
  },
  {
    tenant_id: 1,
    quiz_attempt_id: 1,
    quiz_question_id: 2,
    quiz_question_option_id: 4,
    answer_text: null,
    is_correct: true,
    marks_obtained: 2.0,
    reviewed_by_teacher_id: 1,
    teacher_comment: 'Correct answer.',
    is_active: true,
    is_deleted: false,
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    updated_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    created_by: 1,
    updated_by: 1,
    deleted_at: null,
    deleted_by: null,
    created_ip: '13.3.1.3',
    updated_ip: '13.3.1.4',
  },
  {
    tenant_id: 1,
    quiz_attempt_id: 1,
    quiz_question_id: 3,
    quiz_question_option_id: 7,
    answer_text: null,
    is_correct: true,
    marks_obtained: 1.0,
    reviewed_by_teacher_id: 1,
    teacher_comment: 'Correct answer.',
    is_active: true,
    is_deleted: false,
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    updated_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    created_by: 1,
    updated_by: 1,
    deleted_at: null,
    deleted_by: null,
    created_ip: '13.3.1.5',
    updated_ip: '13.3.1.6',
  },
  // Alex Smith (attempt 2, quiz 2)
  {
    tenant_id: 1,
    quiz_attempt_id: 2,
    quiz_question_id: 4,
    quiz_question_option_id: 14,
    answer_text: null,
    is_correct: true,
    marks_obtained: 3.0,
    reviewed_by_teacher_id: 2,
    teacher_comment: 'Correct answer.',
    is_active: true,
    is_deleted: false,
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    updated_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    created_by: 2,
    updated_by: 2,
    deleted_at: null,
    deleted_by: null,
    created_ip: '13.3.1.7',
    updated_ip: '13.3.1.8',
  },
  {
    tenant_id: 1,
    quiz_attempt_id: 2,
    quiz_question_id: 5,
    quiz_question_option_id: 12,
    answer_text: null,
    is_correct: true,
    marks_obtained: 2.0,
    reviewed_by_teacher_id: 2,
    teacher_comment: 'Correct answer.',
    is_active: true,
    is_deleted: false,
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    updated_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    created_by: 2,
    updated_by: 2,
    deleted_at: null,
    deleted_by: null,
    created_ip: '13.3.1.9',
    updated_ip: '13.3.2.0',
  },
  // Emma Müller (attempt 3, quiz 3, in progress, only one question answered)
  {
    tenant_id: 1,
    quiz_attempt_id: 3,
    quiz_question_id: 6,
    quiz_question_option_id: 16,
    answer_text: null,
    is_correct: true,
    marks_obtained: 2.0,
    reviewed_by_teacher_id: 3,
    teacher_comment: 'Correct answer.',
    is_active: true,
    is_deleted: false,
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    updated_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    created_by: 3,
    updated_by: 3,
    deleted_at: null,
    deleted_by: null,
    created_ip: '13.3.2.1',
    updated_ip: '13.3.2.2',
  },
];
