
// Seed data for quiz question options
export const quiz_question_options = [
  // Q1: Python file extension
  {
    tenant_id: 1,
    quiz_question_id: 1,
    option_text: '.py',
    position: 1,
    is_correct: true,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '12.4.1.1',
    updated_ip: '12.4.1.2',
  },
  {
    tenant_id: 1,
    quiz_question_id: 1,
    option_text: '.python',
    position: 2,
    is_correct: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '12.4.1.3',
    updated_ip: '12.4.1.4',
  },
  {
    tenant_id: 1,
    quiz_question_id: 1,
    option_text: '.pt',
    position: 3,
    is_correct: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '12.4.1.5',
    updated_ip: '12.4.1.6',
  },
  // Q2: Valid variable name
  {
    tenant_id: 1,
    quiz_question_id: 2,
    option_text: 'my_var',
    position: 1,
    is_correct: true,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '12.4.1.7',
    updated_ip: '12.4.1.8',
  },
  {
    tenant_id: 1,
    quiz_question_id: 2,
    option_text: '2var',
    position: 2,
    is_correct: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '12.4.1.9',
    updated_ip: '12.4.2.0',
  },
  {
    tenant_id: 1,
    quiz_question_id: 2,
    option_text: 'var-2',
    position: 3,
    is_correct: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '12.4.2.1',
    updated_ip: '12.4.2.2',
  },
  // Q3: Python is case-sensitive (True/False)
  {
    tenant_id: 1,
    quiz_question_id: 3,
    option_text: 'True',
    position: 1,
    is_correct: true,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '12.4.2.3',
    updated_ip: '12.4.2.4',
  },
  {
    tenant_id: 1,
    quiz_question_id: 3,
    option_text: 'False',
    position: 2,
    is_correct: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '12.4.2.5',
    updated_ip: '12.4.2.6',
  },
  // Q4: NOT a marketing principle
  {
    tenant_id: 1,
    quiz_question_id: 4,
    option_text: 'Product',
    position: 1,
    is_correct: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 2,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '12.4.2.7',
    updated_ip: '12.4.2.8',
  },
  {
    tenant_id: 1,
    quiz_question_id: 4,
    option_text: 'Price',
    position: 2,
    is_correct: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 2,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '12.4.2.9',
    updated_ip: '12.4.3.0',
  },
  {
    tenant_id: 1,
    quiz_question_id: 4,
    option_text: 'Promotion',
    position: 3,
    is_correct: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 2,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '12.4.3.1',
    updated_ip: '12.4.3.2',
  },
  {
    tenant_id: 1,
    quiz_question_id: 4,
    option_text: 'Procrastination',
    position: 4,
    is_correct: true,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 2,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '12.4.3.3',
    updated_ip: '12.4.3.4',
  },
  // Q5: Marketing is only about selling products (True/False)
  {
    tenant_id: 1,
    quiz_question_id: 5,
    option_text: 'True',
    position: 1,
    is_correct: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 2,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '12.4.3.5',
    updated_ip: '12.4.3.6',
  },
  {
    tenant_id: 1,
    quiz_question_id: 5,
    option_text: 'False',
    position: 2,
    is_correct: true,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 2,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '12.4.3.7',
    updated_ip: '12.4.3.8',
  },
  // Q6: Renewable energy source
  {
    tenant_id: 1,
    quiz_question_id: 6,
    option_text: 'Solar',
    position: 1,
    is_correct: true,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 3,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '12.4.3.9',
    updated_ip: '12.4.4.0',
  },
  {
    tenant_id: 1,
    quiz_question_id: 6,
    option_text: 'Coal',
    position: 2,
    is_correct: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 3,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '12.4.4.1',
    updated_ip: '12.4.4.2',
  },
  {
    tenant_id: 1,
    quiz_question_id: 6,
    option_text: 'Oil',
    position: 3,
    is_correct: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 3,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '12.4.4.3',
    updated_ip: '12.4.4.4',
  },
];
