import { UserType } from '@prisma/client';
// Seed data for role screens
export const role_screens = [
  {
    tenant_id: 1,
    role_type: UserType.STUDENT,
    screen_id: 1,
    can_view: true,
    can_create: false,
    can_edit: false,
    can_delete: false,
    can_export: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: 2,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.20.0.1',
    updated_ip: '10.20.0.2',
  },
  {
    tenant_id: 1,
    role_type: UserType.STUDENT,
    screen_id: 2,
    can_view: true,
    can_create: false,
    can_edit: false,
    can_delete: false,
    can_export: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.20.0.3',
    updated_ip: '10.20.0.4',
  },
  {
    tenant_id: 1,
    role_type: UserType.TEACHER,
    screen_id: 3,
    can_view: true,
    can_create: true,
    can_edit: true,
    can_delete: false,
    can_export: true,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 2,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.20.0.5',
    updated_ip: '10.20.0.6',
  },
  {
    tenant_id: 2,
    role_type: UserType.TEACHER,
    screen_id: 4,
    can_view: true,
    can_create: true,
    can_edit: true,
    can_delete: true,
    can_export: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 2,
    updated_by: 1,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.20.0.7',
    updated_ip: '10.20.0.8',
  },
  {
    tenant_id: 2,
    role_type: UserType.TENANT_ADMIN,
    screen_id: 5,
    can_view: true,
    can_create: true,
    can_edit: true,
    can_delete: false,
    can_export: true,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 3,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.20.0.9',
    updated_ip: '10.20.1.0',
  },
  {
    tenant_id: 3,
    role_type: UserType.TENANT_ADMIN,
    screen_id: 6,
    can_view: true,
    can_create: false,
    can_edit: false,
    can_delete: false,
    can_export: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 3,
    updated_by: 1,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.20.1.1',
    updated_ip: '10.20.1.2',
  },
  {
    tenant_id: 3,
    role_type: UserType.SUPER_ADMIN,
    screen_id: 7,
    can_view: true,
    can_create: true,
    can_edit: true,
    can_delete: true,
    can_export: true,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 4,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.20.1.3',
    updated_ip: '10.20.1.4',
  },
  {
    tenant_id: 4,
    role_type: UserType.SUPER_ADMIN,
    screen_id: 8,
    can_view: true,
    can_create: true,
    can_edit: false,
    can_delete: false,
    can_export: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 4,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.20.1.5',
    updated_ip: '10.20.1.6',
  },
  {
    tenant_id: 4,
    role_type: UserType.TEACHER,
    screen_id: 9,
    can_view: true,
    can_create: false,
    can_edit: false,
    can_delete: false,
    can_export: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 2,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.20.1.7',
    updated_ip: '10.20.1.8',
  },
  {
    tenant_id: 4,
    role_type: UserType.STUDENT,
    screen_id: 10,
    can_view: true,
    can_create: false,
    can_edit: false,
    can_delete: false,
    can_export: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.20.1.9',
    updated_ip: '10.20.2.0',
  },
];
