// Seed data for screens
export const screens = [
  {
    screen_name: 'Dashboard',
    screen_description: 'Main analytics and summary view',
    route_path: '/dashboard',
    parent_screen_id: null,
    sort_order: 1,
    icon_class: 'fas fa-home',
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: 2,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.0.1.1',
    updated_ip: '10.0.1.2',
  },
  {
    screen_name: 'Users',
    screen_description: 'User management section',
    route_path: '/users',
    parent_screen_id: null,
    sort_order: 2,
    icon_class: 'fas fa-users',
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.0.1.3',
    updated_ip: '10.0.1.4',
  },
  {
    screen_name: 'User List',
    screen_description: 'View all system users',
    route_path: '/users/list',
    parent_screen_id: 2,
    sort_order: 1,
    icon_class: 'fas fa-list',
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.0.1.5',
    updated_ip: '10.0.1.6',
  },
  {
    screen_name: 'User Roles',
    screen_description: 'Define roles and permissions',
    route_path: '/users/roles',
    parent_screen_id: 2,
    sort_order: 2,
    icon_class: 'fas fa-user-shield',
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.0.1.7',
    updated_ip: '10.0.1.8',
  },
  {
    screen_name: 'Clients',
    screen_description: 'Client account management',
    route_path: '/clients',
    parent_screen_id: null,
    sort_order: 3,
    icon_class: 'fas fa-briefcase',
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 2,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.0.1.9',
    updated_ip: '10.0.2.0',
  },
  {
    screen_name: 'Tenants',
    screen_description: 'Manage tenant organizations',
    route_path: '/tenants',
    parent_screen_id: null,
    sort_order: 4,
    icon_class: 'fas fa-building',
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 2,
    updated_by: 1,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.0.2.1',
    updated_ip: '10.0.2.2',
  },
  {
    screen_name: 'Reports',
    screen_description: 'Analytics and reporting area',
    route_path: '/reports',
    parent_screen_id: null,
    sort_order: 5,
    icon_class: 'fas fa-chart-bar',
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 3,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.0.2.3',
    updated_ip: '10.0.2.4',
  },
  {
    screen_name: 'Create Report',
    screen_description: 'Wizard to create a new report',
    route_path: '/reports/new',
    parent_screen_id: 7,
    sort_order: 1,
    icon_class: 'fas fa-plus-circle',
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 3,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.0.2.5',
    updated_ip: '10.0.2.6',
  },
  {
    screen_name: 'Settings',
    screen_description: 'System-wide configuration area',
    route_path: '/settings',
    parent_screen_id: null,
    sort_order: 6,
    icon_class: 'fas fa-cogs',
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 4,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.0.2.7',
    updated_ip: '10.0.2.8',
  },
  {
    screen_name: 'Audit Logs',
    screen_description: 'Track system activity logs',
    route_path: '/settings/audit-logs',
    parent_screen_id: 9,
    sort_order: 1,
    icon_class: 'fas fa-clipboard-list',
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 4,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.0.2.9',
    updated_ip: '10.0.3.0',
  },
];
