// Specialization-Program Join Table (Many-to-Many)
// Direct relationships from specializations table
// (see development-data-seeding.sql for reference)
export const specialization_programs = [
  {
    specialization_id: 1,
    program_id: 1,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.1.2.1',
    updated_ip: '10.1.2.2'
  },
  {
    specialization_id: 2,
    program_id: 1,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.1.2.3',
    updated_ip: '10.1.2.4'
  },
  {
    specialization_id: 3,
    program_id: 2,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 2,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.1.2.5',
    updated_ip: '10.1.2.6'
  },
  {
    specialization_id: 4,
    program_id: 2,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 2,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.1.2.7',
    updated_ip: '10.1.2.8'
  },
  {
    specialization_id: 5,
    program_id: 3,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 3,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.1.2.9',
    updated_ip: '10.1.3.0'
  },
  {
    specialization_id: 6,
    program_id: 5,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 5,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.1.3.1',
    updated_ip: '10.1.3.2'
  },
  {
    specialization_id: 1,
    program_id: 4,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 4,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.1.3.3',
    updated_ip: '10.1.3.4'
  },
  {
    specialization_id: 2,
    program_id: 2,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 2,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.1.3.5',
    updated_ip: '10.1.3.6'
  },
  {
    specialization_id: 3,
    program_id: 5,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 5,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.1.3.7',
    updated_ip: '10.1.3.8'
  },
  {
    specialization_id: 4,
    program_id: 3,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 3,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.1.3.9',
    updated_ip: '10.1.4.0'
  },
  {
    specialization_id: 5,
    program_id: 4,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 4,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.1.4.1',
    updated_ip: '10.1.4.2'
  },
  {
    specialization_id: 6,
    program_id: 2,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 2,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.1.4.3',
    updated_ip: '10.1.4.4'
  }
];
