// Seed data for specializations
export const specializations = [
  {
    tenant_id: 1,
    program_id: 1,
    specialization_name: 'Software Engineering',
    specialization_thumbnail_url: null,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.1.2.1',
    updated_ip: '10.1.2.2',
  },
  {
    tenant_id: 1,
    program_id: 1,
    specialization_name: 'Data Science',
    specialization_thumbnail_url: null,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.1.2.3',
    updated_ip: '10.1.2.4',
  },
  {
    tenant_id: 2,
    program_id: 2,
    specialization_name: 'Marketing',
    specialization_thumbnail_url: null,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 2,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.1.2.5',
    updated_ip: '10.1.2.6',
  },
  {
    tenant_id: 2,
    program_id: 2,
    specialization_name: 'Finance',
    specialization_thumbnail_url: null,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 2,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.1.2.7',
    updated_ip: '10.1.2.8',
  },
  {
    tenant_id: 3,
    program_id: 3,
    specialization_name: 'Renewable Energy',
    specialization_thumbnail_url: null,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 3,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.1.2.9',
    updated_ip: '10.1.3.0',
  },
  {
    tenant_id: 5,
    program_id: 5,
    specialization_name: 'Clinical Psychology',
    specialization_thumbnail_url: null,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 5,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.1.3.1',
    updated_ip: '10.1.3.2',
  },
];
