// Seed data for states
export const states = [
  {
    country_id: 1,
    name: 'California',
    state_code: 'CA',
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: 2,
    deleted_at: null,
    deleted_by: null,
    created_ip: '192.168.0.1',
    updated_ip: '192.168.0.2',
  },
  {
    country_id: 1,
    name: 'Texas',
    state_code: 'TX',
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '192.168.0.3',
    updated_ip: '192.168.0.4',
  },
  {
    country_id: 2,
    name: 'Ontario',
    state_code: 'ON',
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 2,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '192.168.0.5',
    updated_ip: '192.168.0.6',
  },
  {
    country_id: 2,
    name: 'British Columbia',
    state_code: 'BC',
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 2,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '192.168.0.7',
    updated_ip: '192.168.0.8',
  },
  {
    country_id: 3,
    name: 'England',
    state_code: 'ENG',
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 3,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '192.168.0.9',
    updated_ip: '192.168.1.0',
  },
  {
    country_id: 4,
    name: 'New South Wales',
    state_code: 'NSW',
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 4,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '192.168.1.1',
    updated_ip: '192.168.1.2',
  },
  {
    country_id: 5,
    name: 'Bavaria',
    state_code: 'BY',
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 5,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '192.168.1.3',
    updated_ip: '192.168.1.4',
  },
  {
    country_id: 6,
    name: 'Maharashtra',
    state_code: 'MH',
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 6,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '192.168.1.5',
    updated_ip: '192.168.1.6',
  },
  {
    country_id: 7,
    name: 'Punjab',
    state_code: 'PB',
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 7,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '192.168.1.7',
    updated_ip: '192.168.1.8',
  },
  {
    country_id: 8,
    name: 'Île-de-France',
    state_code: 'IDF',
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 8,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '192.168.1.9',
    updated_ip: '192.168.2.0',
  },
];
