import { DeviceType } from "@prisma/client";
// Seed data for student devices
// All fields mapped from SQL, robust and type-safe
export const student_devices = [
  {
    tenant_id: 1,
    student_id: 1,
    device_type: DeviceType.DESKTOP, // 'LAPTOP' mapped to DESKTOP
    device_identifier: 'LAPTOP-ALPHA-001',
    device_ip: '192.168.10.11',
    mac_address: '00:1A:2B:3C:4D:5E',
    is_primary: true,
    last_active_at: new Date(),
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.33.1.1',
    updated_ip: '10.33.1.2',
  },
  {
    tenant_id: 2,
    student_id: 2,
    device_type: DeviceType.ANDROID, // 'SMARTPHONE' mapped to ANDROID
    device_identifier: 'PHONE-BETA-002',
    device_ip: '192.168.10.12',
    mac_address: '00:1A:2B:3C:4D:5F',
    is_primary: true,
    last_active_at: new Date(),
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 2,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.33.1.3',
    updated_ip: '10.33.1.4',
  },
  {
    tenant_id: 3,
    student_id: 3,
    device_type: DeviceType.WEB, // 'TABLET' mapped to WEB
    device_identifier: 'TABLET-GAMMA-003',
    device_ip: '192.168.10.13',
    mac_address: '00:1A:2B:3C:4D:60',
    is_primary: true,
    last_active_at: new Date(),
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 3,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.33.1.5',
    updated_ip: '10.33.1.6',
  },
  {
    tenant_id: 4,
    student_id: 4,
    device_type: DeviceType.DESKTOP,
    device_identifier: 'DESKTOP-DELTA-004',
    device_ip: '192.168.10.14',
    mac_address: '00:1A:2B:3C:4D:61',
    is_primary: true,
    last_active_at: new Date(),
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 4,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.33.1.7',
    updated_ip: '10.33.1.8',
  },
  {
    tenant_id: 5,
    student_id: 5,
    device_type: DeviceType.DESKTOP, // 'LAPTOP' mapped to DESKTOP
    device_identifier: 'LAPTOP-EPSILON-005',
    device_ip: '192.168.10.15',
    mac_address: '00:1A:2B:3C:4D:62',
    is_primary: true,
    last_active_at: new Date(),
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 5,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.33.1.9',
    updated_ip: '10.33.2.0',
  },
];