// Seed data for student-institute assignments (many-to-many)
// All fields mapped from SQL, robust and type-safe
export const student_institutes = [
  {
    tenant_id: 1,
    student_id: 1,
    institute_id: 1,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.34.1.1',
    updated_ip: '10.34.1.2',
  },
  {
    tenant_id: 2,
    student_id: 2,
    institute_id: 2,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 2,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.34.1.3',
    updated_ip: '10.34.1.4',
  },
  {
    tenant_id: 3,
    student_id: 3,
    institute_id: 3,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 3,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.34.1.5',
    updated_ip: '10.34.1.6',
  },
  {
    tenant_id: 4,
    student_id: 4,
    institute_id: 4,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 4,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.34.1.7',
    updated_ip: '10.34.1.8',
  },
  {
    tenant_id: 5,
    student_id: 5,
    institute_id: 5,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 5,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.34.1.9',
    updated_ip: '10.34.2.0',
  },
  {
    tenant_id: 1,
    student_id: 1,
    institute_id: 2,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.34.2.1',
    updated_ip: '10.34.2.2',
  },
  {
    tenant_id: 2,
    student_id: 2,
    institute_id: 1,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 2,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.34.2.3',
    updated_ip: '10.34.2.4',
  },
];

