import { SubmissionStatus } from '@prisma/client';

// Seed data for student assignments
// All fields mapped from SQL, robust audit fields, type-safe
// Date math uses Date.now() for relative intervals

export const studentAssignments = [
  // Sarah Johnson (student 1) submitted Assignment 1, graded
  {
    tenant_id: 1,
    assignment_id: 1,
    student_id: 1,
    attempt_number: 1,
    submission_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    submission_status: SubmissionStatus.GRADED,
    grade: 95.0,
    percentage: 95.0,
    feedback: 'Great job!',
    graded_by: 1,
    graded_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    teacher_notes: 'Well done.',
    is_late_submission: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    updated_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    created_by: 1,
    updated_by: 1,
    deleted_at: null,
    deleted_by: null,
    created_ip: '15.1.1.1',
    updated_ip: '15.1.1.2',
  },
  // Alex Smith (student 2) submitted Assignment 2, pending grading
  {
    tenant_id: 1,
    assignment_id: 2,
    student_id: 2,
    attempt_number: 1,
    submission_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    submission_status: SubmissionStatus.SUBMITTED,
    grade: null,
    percentage: null,
    feedback: null,
    graded_by: null,
    graded_at: null,
    teacher_notes: null,
    is_late_submission: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    updated_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    created_by: 2,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '15.1.1.3',
    updated_ip: '15.1.1.4',
  },
  // Emma Müller (student 3) not yet submitted Assignment 3
  {
    tenant_id: 1,
    assignment_id: 3,
    student_id: 3,
    attempt_number: 1,
    submission_date: null,
    submission_status: SubmissionStatus.NOT_SUBMITTED,
    grade: null,
    percentage: null,
    feedback: null,
    graded_by: null,
    graded_at: null,
    teacher_notes: null,
    is_late_submission: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 3,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '15.1.1.5',
    updated_ip: '15.1.1.6',
  },
  // Matthew Chen (student 4) submitted Assignment 4 late, graded
  {
    tenant_id: 1,
    assignment_id: 4,
    student_id: 4,
    attempt_number: 1,
    submission_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    submission_status: SubmissionStatus.GRADED,
    grade: 88.0,
    percentage: 88.0,
    feedback: 'Late but good.',
    graded_by: 2,
    graded_at: new Date(),
    teacher_notes: 'Check late penalty.',
    is_late_submission: true,
    is_active: true,
    is_deleted: false,
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    updated_at: new Date(),
    created_by: 4,
    updated_by: 2,
    deleted_at: null,
    deleted_by: null,
    created_ip: '15.1.1.7',
    updated_ip: '15.1.1.8',
  },
  // Alina Patel (student 5) submitted Assignment 5, pending grading
  {
    tenant_id: 1,
    assignment_id: 5,
    student_id: 5,
    attempt_number: 1,
    submission_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    submission_status: SubmissionStatus.SUBMITTED,
    grade: null,
    percentage: null,
    feedback: null,
    graded_by: null,
    graded_at: null,
    teacher_notes: null,
    is_late_submission: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    updated_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    created_by: 5,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '15.1.1.9',
    updated_ip: '15.1.2.0',
  },
];

export default studentAssignments;
