// Seed data for student phone numbers
// All fields mapped from SQL, robust and type-safe
export const student_phone_numbers = [
  {
    tenant_id: 1,
    student_id: 1,
    dial_code: '+1',
    phone_number: '2025550185',
    iso_country_code: 'US',
    is_primary: true,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.32.1.1',
    updated_ip: '10.32.1.2',
  },
  {
    tenant_id: 2,
    student_id: 2,
    dial_code: '+44',
    phone_number: '2079460958',
    iso_country_code: 'GB',
    is_primary: true,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 2,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.32.1.3',
    updated_ip: '10.32.1.4',
  },
  {
    tenant_id: 3,
    student_id: 3,
    dial_code: '+49',
    phone_number: '8923456789',
    iso_country_code: 'DE',
    is_primary: true,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 3,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.32.1.5',
    updated_ip: '10.32.1.6',
  },
  {
    tenant_id: 4,
    student_id: 4,
    dial_code: '+61',
    phone_number: '412345678',
    iso_country_code: 'AU',
    is_primary: true,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 4,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.32.1.7',
    updated_ip: '10.32.1.8',
  },
  {
    tenant_id: 5,
    student_id: 5,
    dial_code: '+91',
    phone_number: '9876543210',
    iso_country_code: 'IN',
    is_primary: true,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 5,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.32.1.9',
    updated_ip: '10.32.2.0',
  },
];
