import { Gender, StudentStatus } from '@prisma/client';
/**
 * Password Hashing Note:
 * ----------------------
 * The 'password' field should contain a plain password for each student.
 * The seeder will hash this value at runtime using the project's hashPassword utility.
 * Do NOT include a 'password_hash' field in this file.
 */
// Seed data for students
export const students = [
  {
    tenant_id: 1,
    full_name: 'Sarah Johnson',
    first_name: 'Sarah',
    middle_name: null,
    last_name: 'Johnson',
    country_id: 1,
    state_id: 1,
    city_id: 1,
    address: '123 Main St, Los Angeles, CA',
    date_of_birth: new Date('2002-05-14'),
    profile_picture_url: null,
    zip_code: '90001',
    age: 22,
    gender: Gender.FEMALE,
    username: 'sarah.j',
    password: 'Password123!',
    last_login_at: new Date(),
    student_status: StudentStatus.ACTIVE,
    referral_type: null,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.30.1.1',
    updated_ip: '10.30.1.2',
  },
  {
    tenant_id: 2,
    full_name: 'Alex Smith',
    first_name: 'Alex',
    middle_name: null,
    last_name: 'Smith',
    country_id: 2,
    state_id: 3,
    city_id: 4,
    address: '45 Park Lane, London',
    date_of_birth: new Date('2001-09-22'),
    profile_picture_url: null,
    zip_code: 'W1K 1PN',
    age: 23,
    gender: Gender.MALE,
    username: 'alex.s',
    password: 'Password123!',
    last_login_at: new Date(),
    student_status: StudentStatus.ACTIVE,
    referral_type: null,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 2,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.30.1.3',
    updated_ip: '10.30.1.4',
  },
  {
    tenant_id: 3,
    full_name: 'Emma Müller',
    first_name: 'Emma',
    middle_name: null,
    last_name: 'Müller',
    country_id: 5,
    state_id: 5,
    city_id: 7,
    address: 'Bavaria, Munich',
    date_of_birth: new Date('2003-03-10'),
    profile_picture_url: null,
    zip_code: '80331',
    age: 21,
    gender: Gender.FEMALE,
    username: 'emma.m',
    password: 'Password123!',
    last_login_at: new Date(),
    student_status: StudentStatus.ACTIVE,
    referral_type: null,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 3,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.30.1.5',
    updated_ip: '10.30.1.6',
  },
  {
    tenant_id: 4,
    full_name: 'Matthew Chen',
    first_name: 'Matthew',
    middle_name: null,
    last_name: 'Chen',
    country_id: 4,
    state_id: 6,
    city_id: 8,
    address: 'Sydney, Australia',
    date_of_birth: new Date('2000-12-01'),
    profile_picture_url: null,
    zip_code: '2000',
    age: 24,
    gender: Gender.MALE,
    username: 'matthew.c',
    password: 'Password123!',
    last_login_at: new Date(),
    student_status: StudentStatus.ACTIVE,
    referral_type: null,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 4,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.30.1.7',
    updated_ip: '10.30.1.8',
  },
  {
    tenant_id: 5,
    full_name: 'Alina Patel',
    first_name: 'Alina',
    middle_name: null,
    last_name: 'Patel',
    country_id: 6,
    state_id: 8,
    city_id: 10,
    address: 'Mumbai, India',
    date_of_birth: new Date('2002-07-19'),
    profile_picture_url: null,
    zip_code: '400001',
    age: 22,
    gender: Gender.FEMALE,
    username: 'alina.p',
    password: 'Password123!',
    last_login_at: new Date(),
    student_status: StudentStatus.ACTIVE,
    referral_type: null,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 5,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.30.1.9',
    updated_ip: '10.30.2.0',
  },
];
