// Seed data for student email addresses
// All fields mapped from SQL, robust and type-safe
export const student_email_addresses = [
  {
    tenant_id: 1,
    student_id: 1,
    email_address: 'maaz@hussaini.edu',
    is_primary: true,
    priority: 1,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.31.1.1',
    updated_ip: '10.31.1.2',
  },
  {
    tenant_id: 2,
    student_id: 2,
    email_address: 'alex.smith@beta-school.edu',
    is_primary: true,
    priority: 1,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 2,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.31.1.3',
    updated_ip: '10.31.1.4',
  },
  {
    tenant_id: 3,
    student_id: 3,
    email_address: 'emma.muller@gamma-learning.edu',
    is_primary: true,
    priority: 1,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 3,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.31.1.5',
    updated_ip: '10.31.1.6',
  },
  {
    tenant_id: 4,
    student_id: 4,
    email_address: 'matthew.chen@delta-institute.edu',
    is_primary: true,
    priority: 1,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 4,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.31.1.7',
    updated_ip: '10.31.1.8',
  },
  {
    tenant_id: 5,
    student_id: 5,
    email_address: 'alina.patel@epsilon-univ.edu',
    is_primary: true,
    priority: 1,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 5,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.31.1.9',
    updated_ip: '10.31.2.0',
  },
];
