import { UserType, SystemUserStatus } from '@prisma/client';
// Seed data for system users
export const system_users = [
  {
    tenant_id: 1,
    role_type: UserType.TENANT_ADMIN,
    username: 'admin_alpha',
    full_name: 'Alice Johnson',
    email_address: 'alice@alpha.com',
    password_hash: 'hashed_pw_1',
    last_login_at: new Date(),
    login_attempts: 0,
    system_user_status: SystemUserStatus.ACTIVE,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: 2,
    deleted_at: null,
    deleted_by: null,
    created_ip: '192.168.100.1',
    updated_ip: '192.168.100.2',
  },
  {
    tenant_id: 1,
    role_type: UserType.TENANT_ADMIN,
    username: 'beta_support',
    full_name: 'Bob Smith',
    email_address: 'bob@beta.com',
    password_hash: 'hashed_pw_2',
    last_login_at: null,
    login_attempts: 3,
    system_user_status: SystemUserStatus.LOCKED,
    is_active: false,
    is_deleted: true,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 2,
    updated_by: 1,
    deleted_at: new Date(),
    deleted_by: 1,
    created_ip: '192.168.100.3',
    updated_ip: '192.168.100.4',
  },
  {
    tenant_id: 2,
    role_type: UserType.TENANT_ADMIN,
    username: 'gamma_admin',
    full_name: 'Carol Ahmed',
    email_address: 'carol@gamma.com',
    password_hash: 'hashed_pw_3',
    last_login_at: new Date(),
    login_attempts: 1,
    system_user_status: SystemUserStatus.SUSPENDED,
    is_active: false,
    is_deleted: true,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 3,
    updated_by: null,
    deleted_at: new Date(),
    deleted_by: 2,
    created_ip: '192.168.100.5',
    updated_ip: '192.168.100.6',
  },
  {
    tenant_id: 2,
    role_type: UserType.SUPER_ADMIN,
    username: 'superadmin',
    full_name: 'David Wang',
    email_address: 'david@sys.com',
    password_hash: 'hashed_pw_4',
    last_login_at: new Date(),
    login_attempts: 0,
    system_user_status: SystemUserStatus.ACTIVE,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 4,
    updated_by: 1,
    deleted_at: null,
    deleted_by: null,
    created_ip: '192.168.100.7',
    updated_ip: '192.168.100.8',
  },
  {
    tenant_id: null,
    role_type: UserType.SUPER_ADMIN,
    username: 'sys_op1',
    full_name: 'Eva Lopez',
    email_address: 'eva@sys.com',
    password_hash: 'hashed_pw_5',
    last_login_at: null,
    login_attempts: 2,
    system_user_status: SystemUserStatus.INACTIVE,
    is_active: false,
    is_deleted: true,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: new Date(),
    deleted_by: 3,
    created_ip: '192.168.100.9',
    updated_ip: '192.168.101.0',
  },
  {
    tenant_id: 3,
    role_type: UserType.TENANT_ADMIN,
    username: 'delta_admin',
    full_name: 'Frank Müller',
    email_address: 'frank@delta.com',
    password_hash: 'hashed_pw_6',
    last_login_at: new Date(),
    login_attempts: 0,
    system_user_status: SystemUserStatus.ACTIVE,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 2,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '192.168.101.1',
    updated_ip: '192.168.101.2',
  },
  {
    tenant_id: null,
    role_type: UserType.SUPER_ADMIN,
    username: 'root_user',
    full_name: 'Grace Chen',
    email_address: 'grace@root.com',
    password_hash: 'hashed_pw_7',
    last_login_at: new Date(),
    login_attempts: 0,
    system_user_status: SystemUserStatus.ACTIVE,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 3,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '192.168.101.3',
    updated_ip: '192.168.101.4',
  },
  {
    tenant_id: 3,
    role_type: UserType.TENANT_ADMIN,
    username: 'eps_admin',
    full_name: 'Hassan Ali',
    email_address: 'hassan@eps.com',
    password_hash: 'hashed_pw_8',
    last_login_at: null,
    login_attempts: 0,
    system_user_status: SystemUserStatus.ACTIVE,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 4,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '192.168.101.5',
    updated_ip: '192.168.101.6',
  },
  {
    tenant_id: null,
    role_type: UserType.SUPER_ADMIN,
    username: 'auditor',
    full_name: 'Iris Becker',
    email_address: 'iris@audit.com',
    password_hash: 'hashed_pw_9',
    last_login_at: new Date(),
    login_attempts: 1,
    system_user_status: SystemUserStatus.SUSPENDED,
    is_active: false,
    is_deleted: true,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: new Date(),
    deleted_by: 2,
    created_ip: '192.168.101.7',
    updated_ip: '192.168.101.8',
  },
  {
    tenant_id: 4,
    role_type: UserType.TENANT_ADMIN,
    username: 'zeta_ops',
    full_name: 'John Lee',
    email_address: 'john@zeta.com',
    password_hash: 'hashed_pw_10',
    last_login_at: new Date(),
    login_attempts: 0,
    system_user_status: SystemUserStatus.ACTIVE,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 2,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '192.168.101.9',
    updated_ip: '192.168.102.0',
  },
];
