import { Gender } from '@prisma/client';
/**
 * Password Hashing Note:
 * ----------------------
 * The 'password' field should contain a plain password for each teacher.
 * The seeder will hash this value at runtime using the project's hashPassword utility.
 * Do NOT include a 'password_hash' field in this file.
 */
// Seed data for teachers
export const teachers = [
  {
    tenant_id: 1,
    full_name: 'Omar Altaf',
    first_name: 'Omar',
    middle_name: null,
    last_name: 'Altaf',
    country_id: 1,
    state_id: 1,
    city_id: 1,
    address: '456 University Ave',
    date_of_birth: new Date('1975-04-12'),
    profile_picture_url: null,
    zip_code: '90001',
    age: 50,
    gender: Gender.MALE,
    username: 'john.w',
    password: 'Password123!',
    last_login_at: new Date(),
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.40.1.1',
    updated_ip: '10.40.1.2'
  },
  {
    tenant_id: 1,
    full_name: 'Shah Hasan',
    first_name: 'Shah',
    middle_name: null,
    last_name: 'Hasan',
    country_id: 1,
    state_id: 1,
    city_id: 1,
    address: '456 University Ave',
    date_of_birth: new Date('1975-04-12'),
    profile_picture_url: null,
    zip_code: '90001',
    age: 50,
    gender: Gender.MALE,
    username: 'john.w',
    password: 'Password123!',
    last_login_at: new Date(),
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.40.1.1',
    updated_ip: '10.40.1.2'
  },
  {
    tenant_id: 1,
    full_name: 'Zarak Mushtaq',
    first_name: 'Zarak',
    middle_name: null,
    last_name: 'Mushtaq',
    country_id: 1,
    state_id: 1,
    city_id: 1,
    address: '456 University Ave',
    date_of_birth: new Date('1975-04-12'),
    profile_picture_url: null,
    zip_code: '90001',
    age: 50,
    gender: Gender.MALE,
    username: 'john.w',
    password: 'Password123!',
    last_login_at: new Date(),
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.40.1.1',
    updated_ip: '10.40.1.2'
  },
  {
    tenant_id: 1,
    full_name: 'Salman Mustafa',
    first_name: 'Salman',
    middle_name: null,
    last_name: 'Mustafa',
    country_id: 1,
    state_id: 1,
    city_id: 1,
    address: '456 University Ave',
    date_of_birth: new Date('1975-04-12'),
    profile_picture_url: null,
    zip_code: '90001',
    age: 50,
    gender: Gender.MALE,
    username: 'john.w',
    password: 'Password123!',
    last_login_at: new Date(),
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.40.1.1',
    updated_ip: '10.40.1.2'
  },
];