import { Gender } from '@prisma/client';
// Seed data for teachers
export const teachers = [
  {
    tenant_id: 1,
    full_name: 'Dr. John Williams',
    first_name: 'John',
    middle_name: null,
    last_name: 'Williams',
    country_id: 1,
    state_id: 1,
    city_id: 1,
    address: '456 University Ave, Los Angeles, CA',
    date_of_birth: new Date('1975-04-12'),
    profile_picture_url: null,
    zip_code: '90001',
    age: 50,
    gender: Gender.MALE,
    username: 'john.w',
    password_hash: 'hashed_pw_21',
    last_login_at: new Date(),
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.40.1.1',
    updated_ip: '10.40.1.2',
  },
  {
    tenant_id: 2,
    full_name: 'Prof. Emily Clark',
    first_name: 'Emily',
    middle_name: null,
    last_name: 'Clark',
    country_id: 2,
    state_id: 3,
    city_id: 4,
    address: '78 Queen St, London',
    date_of_birth: new Date('1980-09-30'),
    profile_picture_url: null,
    zip_code: 'W1K 2QD',
    age: 45,
    gender: Gender.FEMALE,
    username: 'emily.c',
    password_hash: 'hashed_pw_22',
    last_login_at: new Date(),
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 2,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.40.1.3',
    updated_ip: '10.40.1.4',
  },
  {
    tenant_id: 3,
    full_name: 'Dr. Markus Schmidt',
    first_name: 'Markus',
    middle_name: null,
    last_name: 'Schmidt',
    country_id: 5,
    state_id: 5,
    city_id: 7,
    address: 'Universitätsstraße 12, Munich',
    date_of_birth: new Date('1972-06-18'),
    profile_picture_url: null,
    zip_code: '80331',
    age: 53,
    gender: Gender.MALE,
    username: 'markus.s',
    password_hash: 'hashed_pw_23',
    last_login_at: new Date(),
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 3,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.40.1.5',
    updated_ip: '10.40.1.6',
  },
  {
    tenant_id: 4,
    full_name: 'Dr. Priya Nair',
    first_name: 'Priya',
    middle_name: null,
    last_name: 'Nair',
    country_id: 6,
    state_id: 8,
    city_id: 10,
    address: 'Bandra, Mumbai',
    date_of_birth: new Date('1985-11-22'),
    profile_picture_url: null,
    zip_code: '400050',
    age: 39,
    gender: Gender.FEMALE,
    username: 'priya.n',
    password_hash: 'hashed_pw_24',
    last_login_at: new Date(),
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 4,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.40.1.7',
    updated_ip: '10.40.1.8',
  },
  {
    tenant_id: 5,
    full_name: 'Prof. Matthew Evans',
    first_name: 'Matthew',
    middle_name: null,
    last_name: 'Evans',
    country_id: 4,
    state_id: 6,
    city_id: 8,
    address: '123 George St, Sydney',
    date_of_birth: new Date('1978-02-05'),
    profile_picture_url: null,
    zip_code: '2000',
    age: 47,
    gender: Gender.MALE,
    username: 'matthew.e',
    password_hash: 'hashed_pw_25',
    last_login_at: new Date(),
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 5,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.40.1.9',
    updated_ip: '10.40.2.0',
  },
];
