// Seed data for teacher phone numbers
export const teacher_phone_numbers = [
  {
    tenant_id: 1,
    teacher_id: 1,
    dial_code: '+1',
    phone_number: '2135550199',
    iso_country_code: 'US',
    is_primary: true,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.42.1.1',
    updated_ip: '10.42.1.2',
  },
  {
    tenant_id: 2,
    teacher_id: 2,
    dial_code: '+44',
    phone_number: '2079460999',
    iso_country_code: 'GB',
    is_primary: true,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 2,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.42.1.3',
    updated_ip: '10.42.1.4',
  },
  {
    tenant_id: 3,
    teacher_id: 3,
    dial_code: '+49',
    phone_number: '8923456799',
    iso_country_code: 'DE',
    is_primary: true,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 3,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.42.1.5',
    updated_ip: '10.42.1.6',
  },
  {
    tenant_id: 4,
    teacher_id: 4,
    dial_code: '+91',
    phone_number: '9812345679',
    iso_country_code: 'IN',
    is_primary: true,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 4,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.42.1.7',
    updated_ip: '10.42.1.8',
  },
  {
    tenant_id: 5,
    teacher_id: 5,
    dial_code: '+61',
    phone_number: '412345679',
    iso_country_code: 'AU',
    is_primary: true,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 5,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.42.1.9',
    updated_ip: '10.42.2.0',
  },
];
