// Seed data for teacher email addresses
export const teacher_email_addresses = [
  {
    tenant_id: 1,
    teacher_id: 1,
    email_address: 'john.williams@alpha-academy.edu',
    is_primary: true,
    priority: 1,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.41.1.1',
    updated_ip: '10.41.1.2',
  },
  {
    tenant_id: 2,
    teacher_id: 2,
    email_address: 'emily.clark@beta-school.edu',
    is_primary: true,
    priority: 1,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 2,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.41.1.3',
    updated_ip: '10.41.1.4',
  },
  {
    tenant_id: 3,
    teacher_id: 3,
    email_address: 'markus.schmidt@gamma-learning.edu',
    is_primary: true,
    priority: 1,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 3,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.41.1.5',
    updated_ip: '10.41.1.6',
  },
  {
    tenant_id: 4,
    teacher_id: 4,
    email_address: 'priya.nair@epsilon-univ.edu',
    is_primary: true,
    priority: 1,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 4,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.41.1.7',
    updated_ip: '10.41.1.8',
  },
  {
    tenant_id: 5,
    teacher_id: 5,
    email_address: 'matthew.evans@delta-institute.edu',
    is_primary: true,
    priority: 1,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 5,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.41.1.9',
    updated_ip: '10.41.2.0',
  },
];
