import { ContactType } from "@prisma/client";
// Seed data for tenant phone numbers
export const tenant_phone_numbers = [
  {
    tenant_id: 1,
    dial_code: '1',
    phone_number: '1234567890',
    iso_country_code: 'US',
    is_primary: true,
    contact_type: ContactType.PRIMARY,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: 2,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.10.1.1',
    updated_ip: '10.10.1.2',
  },
  {
    tenant_id: 1,
    dial_code: '1',
    phone_number: '1234567891',
    iso_country_code: 'US',
    is_primary: false,
    contact_type: ContactType.SECONDARY,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.10.1.3',
    updated_ip: '10.10.1.4',
  },
  {
    tenant_id: 2,
    dial_code: '44',
    phone_number: '7700123456',
    iso_country_code: 'GB',
    is_primary: true,
    contact_type: ContactType.PRIMARY,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 2,
    updated_by: 3,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.10.1.5',
    updated_ip: '10.10.1.6',
  },
  {
    tenant_id: 2,
    dial_code: '44',
    phone_number: '7700123457',
    iso_country_code: 'GB',
    is_primary: false,
    contact_type: ContactType.EMERGENCY,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 2,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.10.1.7',
    updated_ip: '10.10.1.8',
  },
  {
    tenant_id: 3,
    dial_code: '92',
    phone_number: '3001234567',
    iso_country_code: 'PK',
    is_primary: true,
    contact_type: ContactType.PRIMARY,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 3,
    updated_by: 1,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.10.1.9',
    updated_ip: '10.10.2.0',
  },
  {
    tenant_id: 3,
    dial_code: '92',
    phone_number: '3012345678',
    iso_country_code: 'PK',
    is_primary: false,
    contact_type: ContactType.BILLING,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 3,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.10.2.1',
    updated_ip: '10.10.2.2',
  },
  {
    tenant_id: 4,
    dial_code: '61',
    phone_number: '412345678',
    iso_country_code: 'AU',
    is_primary: true,
    contact_type: ContactType.PRIMARY,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 4,
    updated_by: 2,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.10.2.3',
    updated_ip: '10.10.2.4',
  },
  {
    tenant_id: 5,
    dial_code: '34',
    phone_number: '612345678',
    iso_country_code: 'ES',
    is_primary: true,
    contact_type: ContactType.PRIMARY,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 5,
    updated_by: 1,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.10.2.5',
    updated_ip: '10.10.2.6',
  },
  {
    tenant_id: 5,
    dial_code: '34',
    phone_number: '612345679',
    iso_country_code: 'ES',
    is_primary: false,
    contact_type: ContactType.SECONDARY,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 5,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.10.2.7',
    updated_ip: '10.10.2.8',
  },
  {
    tenant_id: 6,
    dial_code: '91',
    phone_number: '9812345678',
    iso_country_code: 'IN',
    is_primary: true,
    contact_type: ContactType.EMERGENCY,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 6,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.10.2.9',
    updated_ip: '10.10.3.0',
  },
];
