// Seed data for tenants
import { TenantStatus } from '@prisma/client';
export const tenants = [
  {
    tenant_name: 'Alpha Academy',
    logo_url_light: 'https://example.com/logo_light1.png',
    logo_url_dark: 'https://example.com/logo_dark1.png',
    favicon_url: 'https://example.com/favicon1.ico',
    theme: {},
    tenant_status: TenantStatus.ACTIVE,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: 2,
    deleted_at: null,
    deleted_by: null,
    created_ip: '192.168.1.1',
    updated_ip: '192.168.1.2',
  },
  {
    tenant_name: 'Beta School',
    logo_url_light: 'https://example.com/logo_light2.png',
    logo_url_dark: 'https://example.com/logo_dark2.png',
    favicon_url: 'https://example.com/favicon2.ico',
    theme: {},
    tenant_status: TenantStatus.TRIAL,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 2,
    updated_by: 3,
    deleted_at: null,
    deleted_by: null,
    created_ip: '192.168.1.3',
    updated_ip: '192.168.1.4',
  },
  {
    tenant_name: 'Gamma Learning',
    logo_url_light: 'https://example.com/logo_light3.png',
    logo_url_dark: 'https://example.com/logo_dark3.png',
    favicon_url: 'https://example.com/favicon3.ico',
    theme: {},
    tenant_status: TenantStatus.SUSPENDED,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 3,
    updated_by: 4,
    deleted_at: null,
    deleted_by: null,
    created_ip: '192.168.1.5',
    updated_ip: '192.168.1.6',
  },
  {
    tenant_name: 'Delta Institute',
    logo_url_light: 'https://example.com/logo_light4.png',
    logo_url_dark: 'https://example.com/logo_dark4.png',
    favicon_url: 'https://example.com/favicon4.ico',
    theme: {},
    tenant_status: TenantStatus.EXPIRED,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 4,
    updated_by: 5,
    deleted_at: null,
    deleted_by: null,
    created_ip: '192.168.1.7',
    updated_ip: '192.168.1.8',
  },
  {
    tenant_name: 'Epsilon University',
    logo_url_light: 'https://example.com/logo_light5.png',
    logo_url_dark: 'https://example.com/logo_dark5.png',
    favicon_url: 'https://example.com/favicon5.ico',
    theme: {},
    tenant_status: TenantStatus.CANCELLED,
    is_active: false,
    is_deleted: true,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 5,
    updated_by: 6,
    deleted_at: new Date(),
    deleted_by: 6,
    created_ip: '192.168.1.9',
    updated_ip: '192.168.2.0',
  },
  {
    tenant_name: 'Zeta College',
    logo_url_light: 'https://example.com/logo_light6.png',
    logo_url_dark: 'https://example.com/logo_dark6.png',
    favicon_url: 'https://example.com/favicon6.ico',
    theme: {},
    tenant_status: TenantStatus.ACTIVE,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '192.168.2.1',
    updated_ip: '192.168.2.2',
  },
  {
    tenant_name: 'Eta Academy',
    logo_url_light: 'https://example.com/logo_light7.png',
    logo_url_dark: 'https://example.com/logo_dark7.png',
    favicon_url: 'https://example.com/favicon7.ico',
    theme: {},
    tenant_status: TenantStatus.ACTIVE,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 2,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '192.168.2.3',
    updated_ip: '192.168.2.4',
  },
  {
    tenant_name: 'Theta School',
    logo_url_light: 'https://example.com/logo_light8.png',
    logo_url_dark: 'https://example.com/logo_dark8.png',
    favicon_url: 'https://example.com/favicon8.ico',
    theme: {},
    tenant_status: TenantStatus.ACTIVE,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 3,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '192.168.2.5',
    updated_ip: '192.168.2.6',
  },
  {
    tenant_name: 'Iota Learning',
    logo_url_light: 'https://example.com/logo_light9.png',
    logo_url_dark: 'https://example.com/logo_dark9.png',
    favicon_url: 'https://example.com/favicon9.ico',
    theme: {},
    tenant_status: TenantStatus.ACTIVE,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 4,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '192.168.2.7',
    updated_ip: '192.168.2.8',
  },
  {
    tenant_name: 'Kappa Institute',
    logo_url_light: 'https://example.com/logo_light10.png',
    logo_url_dark: 'https://example.com/logo_dark10.png',
    favicon_url: 'https://example.com/favicon10.ico',
    theme: {},
    tenant_status: TenantStatus.ACTIVE,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 5,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '192.168.2.9',
    updated_ip: '192.168.3.0',
  },
];
