import { ContactType } from '@prisma/client';
// Seed data for tenant email addresses
export const tenant_email_addresses = [
  {
    tenant_id: 1,
    email_address: 'primary@alpha-academy.com',
    is_primary: true,
    contact_type: ContactType.PRIMARY,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: 2,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.20.0.1',
    updated_ip: '10.20.0.2',
  },
  {
    tenant_id: 1,
    email_address: 'billing@alpha-academy.com',
    is_primary: false,
    contact_type: ContactType.BILLING,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.20.0.3',
    updated_ip: '10.20.0.4',
  },
  {
    tenant_id: 2,
    email_address: 'admin@beta-school.org',
    is_primary: true,
    contact_type: ContactType.PRIMARY,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 2,
    updated_by: 3,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.20.0.5',
    updated_ip: '10.20.0.6',
  },
  {
    tenant_id: 2,
    email_address: 'support@beta-school.org',
    is_primary: false,
    contact_type: ContactType.SECONDARY,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 2,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.20.0.7',
    updated_ip: '10.20.0.8',
  },
  {
    tenant_id: 3,
    email_address: 'emergency@gamma-learning.edu',
    is_primary: false,
    contact_type: ContactType.EMERGENCY,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 3,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.20.0.9',
    updated_ip: '10.20.1.0',
  },
  {
    tenant_id: 3,
    email_address: 'contact@gamma-learning.edu',
    is_primary: true,
    contact_type: ContactType.PRIMARY,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 3,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.20.1.1',
    updated_ip: '10.20.1.2',
  },
  {
    tenant_id: 4,
    email_address: 'info@delta-institute.com',
    is_primary: true,
    contact_type: ContactType.PRIMARY,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 4,
    updated_by: 2,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.20.1.3',
    updated_ip: '10.20.1.4',
  },
  {
    tenant_id: 5,
    email_address: 'billing@epsilon-univ.net',
    is_primary: false,
    contact_type: ContactType.BILLING,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 5,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.20.1.5',
    updated_ip: '10.20.1.6',
  },
  {
    tenant_id: 5,
    email_address: 'admin@epsilon-univ.net',
    is_primary: true,
    contact_type: ContactType.PRIMARY,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 5,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.20.1.7',
    updated_ip: '10.20.1.8',
  },
  {
    tenant_id: 6,
    email_address: 'help@zeta-college.org',
    is_primary: true,
    contact_type: ContactType.PRIMARY,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 6,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.20.1.9',
    updated_ip: '10.20.2.0',
  },
];
