// Seed data for user screens
export const user_screens = [
  {
    tenant_id: 1,
    system_user_id: 1,
    screen_id: 1,
    can_view: true,
    can_create: false,
    can_edit: false,
    can_delete: false,
    can_export: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: 2,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.10.10.1',
    updated_ip: '10.10.10.2',
  },
  {
    tenant_id: 1,
    system_user_id: 1,
    screen_id: 2,
    can_view: true,
    can_create: true,
    can_edit: true,
    can_delete: false,
    can_export: true,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 1,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.10.10.3',
    updated_ip: '10.10.10.4',
  },
  {
    tenant_id: 1,
    system_user_id: 2,
    screen_id: 3,
    can_view: true,
    can_create: false,
    can_edit: false,
    can_delete: false,
    can_export: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 2,
    updated_by: 1,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.10.10.5',
    updated_ip: '10.10.10.6',
  },
  {
    tenant_id: 2,
    system_user_id: 3,
    screen_id: 4,
    can_view: true,
    can_create: true,
    can_edit: true,
    can_delete: true,
    can_export: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 3,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.10.10.7',
    updated_ip: '10.10.10.8',
  },
  {
    tenant_id: 2,
    system_user_id: 4,
    screen_id: 5,
    can_view: true,
    can_create: false,
    can_edit: false,
    can_delete: false,
    can_export: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 4,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.10.10.9',
    updated_ip: '10.10.11.0',
  },
  {
    tenant_id: 3,
    system_user_id: 5,
    screen_id: 6,
    can_view: true,
    can_create: true,
    can_edit: false,
    can_delete: false,
    can_export: true,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 5,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.10.11.1',
    updated_ip: '10.10.11.2',
  },
  {
    tenant_id: 3,
    system_user_id: 6,
    screen_id: 7,
    can_view: true,
    can_create: true,
    can_edit: true,
    can_delete: false,
    can_export: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 6,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.10.11.3',
    updated_ip: '10.10.11.4',
  },
  {
    tenant_id: 4,
    system_user_id: 7,
    screen_id: 8,
    can_view: true,
    can_create: true,
    can_edit: true,
    can_delete: true,
    can_export: true,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 7,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.10.11.5',
    updated_ip: '10.10.11.6',
  },
  {
    tenant_id: 4,
    system_user_id: 8,
    screen_id: 9,
    can_view: true,
    can_create: false,
    can_edit: false,
    can_delete: false,
    can_export: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 8,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.10.11.7',
    updated_ip: '10.10.11.8',
  },
  {
    tenant_id: 4,
    system_user_id: 9,
    screen_id: 10,
    can_view: true,
    can_create: true,
    can_edit: false,
    can_delete: true,
    can_export: false,
    is_active: true,
    is_deleted: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 9,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    created_ip: '10.10.11.9',
    updated_ip: '10.10.12.0',
  },
];
